### ISSUE TITLE
Deprecate LV_LVGL_H_INCLUDE_SIMPLE and change include file layout

### ISSUE THREAD

**Issue by cmumford** [kisvegabor/lvgl#2671]
### Introduce the problem
The layout and use of public header (i.e. include) files is too complicated. The primary LVGL project header file (i.e. `lvgl.h`) is currently located at the top level of the project, and duplicated in the `src` folder.

Others have asked about this, see LVGL [forum question](https://forum.lvgl.io/t/i-dont-understand-this-expression-include-lvgl-lvgl-h/5471), and the response was:

> It’s because not everyone has their include paths configured the same way. There is only one `lvgl.h` file in LVGL, but some users have their include path set to the parent directory (meaning they would have to include `lvgl/lvgl.h`) and others have it set to the lvgl folder (meaning they only need to include `lvgl.h`). The setting is provided to allow choosing between these.

This adds unnecessary complexity to LVGL to solve a problem that already has a cross platform/toolchain solution, which is to add an include path.

### Examples and cases

LVGL currently has the following layout:

```
//lvgl.h
//src/lvgl.h ← includes lvgl.h in parent directory.
```

and when included:

```c
#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif
```

### Suggested solution
Follow a common practice, which is to put all public headers into the `//include/<project>` directory. So, for LVGL it would be:

```
//include/lvgl/lvgl.h
```

Also, **every** header file included by `lvgl.h` (i.e. every public header file) will also be moved to the //include/lvgl folder.

**Deprecate** `LV_LVGL_H_INCLUDE_SIMPLE` so **all** header includes would be:

```c
#include "lvgl/lvgl.h"
```

This also has the benefit of minimizing LVGL's API surface.

At present LVGL contains 160 header files, 110 of which seem to be necessary for
library use - i.e. public headers. These 110 files are those which are included by
`lvgl.h` The other 50 appear to be private:

```
//examples/anim/lv_example_anim.h
//examples/event/lv_example_event.h
//examples/get_started/lv_example_get_started.h
//examples/layouts/flex/lv_example_flex.h
//examples/layouts/grid/lv_example_grid.h
//examples/layouts/lv_example_layout.h
//examples/libs/bmp/lv_example_bmp.h
//examples/libs/freetype/lv_example_freetype.h
//examples/libs/gif/lv_example_gif.h
//examples/libs/lv_example_libs.h
//examples/libs/png/lv_example_png.h
//examples/libs/qrcode/lv_example_qrcode.h
//examples/libs/sjpg/lv_example_sjpg.h
//examples/lv_examples.h
//examples/others/lv_example_others.h
//examples/others/snapshot/lv_example_snapshot.h
//examples/porting/lv_port_disp_template.h
//examples/porting/lv_port_fs_template.h
//examples/porting/lv_port_indev_template.h
//examples/scroll/lv_example_scroll.h
//examples/styles/lv_example_style.h
//examples/widgets/lv_example_widgets.h
//lv_conf_template.h
//src/core/lv_indev_scroll.h
//src/extra/libs/png/lodepng.h
//src/extra/libs/qrcode/qrcodegen.h
//src/extra/libs/sjpg/tjpgdcnf.h
//src/gpu/lv_gpu_nxp_pxp.h
//src/gpu/lv_gpu_nxp_pxp_osa.h
//src/gpu/lv_gpu_nxp_vglite.h
//src/gpu/lv_gpu_sdl.h
//src/gpu/lv_gpu_stm32_dma2d.h
//src/gpu/sdl/lv_gpu_sdl_lru.h
//src/gpu/sdl/lv_gpu_sdl_mask.h
//src/gpu/sdl/lv_gpu_sdl_stack_blur.h
//src/gpu/sdl/lv_gpu_sdl_texture_cache.h
//src/gpu/sdl/lv_gpu_sdl_utils.h
//src/misc/lv_gc.h
//src/misc/lv_templ.h
//src/misc/lv_tlsf.h
//src/misc/lv_txt_ap.h
//src/misc/lv_utils.h
//src/widgets/lv_objx_templ.h
//tests/src/lv_test_conf.h
//tests/src/lv_test_indev.h
//tests/src/lv_test_init.h
//tests/unity/unity.h
//tests/unity/unity_internals.h
//tests/unity/unity_support.h
//test_screenshot_error.h
```

### LVGL user impact
Users would need to add or adjust an include path
to their project files.

### LVGL developer impact
The biggest impact will probably be on developers. Having include files in another directory from their implementation might make things more difficult. In VSCode, using the "Toggle Header/Source" feature **will** successfully toggle in the new proposed layout.  I suspect other editors are smart enough to locate these header files because this is a common practice.

**Comment by cmumford** [comment]
I've done an experiment to see what this change would look like. https://github.com/cmumford/lvgl/tree/simplify-include

**Comment by kisvegabor** [comment]
The main reason why we have 2 `lvgl.h` files now is that Arudino looks for the main include file in the `src` folder. AFAIK (correct me I'm wrong) but the `include` or `inc` folders are not supported in Arduino.

I'd a little bit afraid to change the project structure this way simply because it works in the package managers and SDKs we aware of. I can't foresee how many system could be broken by such change.

The reason of `LV_LVGL_H_INCLUDE_SIMPLE` is also similar. Some systems want to include with `lvgl.h` and others with `lvgl/lvgl.h`.

It's important to keep in mind that some users don't know how to change the build settings and other can't change it because their SDK doesn't make it possible (e.g. Arduino)

The question of private/public headers has a long history mainly to keep the Micropython binding as small as possible. So far we couldn't find a really good approach. The topic was just warmed up [here](https://github.com/lvgl/lvgl/pull/2666) so ideas are welcome :slightly_smiling_face:

**Comment by cmumford** [comment]
Yes, sadly Arduino only looks for [include files in src/](https://arduino.github.io/arduino-cli/0.19/library-specification/#:~:text=only%20the%20src%20folder%20is%20added%20to%20the%20include%20search%20path), and I don't see a way around that. We could have a build step to produce the Arduino library ZIP file with the correct layout, but that would add complexity and make it impossible to work with a live Git cloned repo as an Arduino library. Oh well, it is what it is. 😢

**Comment by xiaoxiang781216** [comment]
Can we keep the duped lvgl.h, but at least remove the ugly code in many source files like this:
```
#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "../../lvgl.h"
#endif
```
BTW, there are many place include lvgl.h by several variant:
```
#include "../lvgl.h"
#include "../../lvgl.h"
#include "../../../lvgl.h"
```
It's better to unify to ether:
```
#include "lvgl.h"
```
or
```
#include "lvgl/lvgl.h"
```

**Comment by kisvegabor** [comment]
> Can we keep the duped lvgl.h, but at least remove the ugly code in many source files like this:

Do you have any suggestions? :slightly_smiling_face: 

E.g. in built in fonts we can keep the relative path only. 

> BTW, there are many place include lvgl.h by several variant:

In `lvgl`? It's to keep lvgl configuration free. Using relative paths the user don't have add new include path to the build to compile lvgl.

**Comment by higaski** [comment]
I agree with the proposal and the solution although I think the real problem lies elsewhere. lv_drivers and lv_demos contain the same dependency to LV_LVGL_H_INCLUDE_SIMPLE and they don't have the option to fallback to relative paths... relative paths to... where? 

At the end of the day a library can't be 100% "configuration free". User who still live in the 20th century will have to copy and paste code around and adjust include paths like it's 1973. For everyone else some kind of build system (e.g. CMake) will do that job for you, but that's currently broken...

**Comment by kisvegabor** [comment]
> relative paths to... where?

In most of the cases I assume `lvgl` and `lv_demos` are next each other.

> For everyone else some kind of build system (e.g. CMake)

The problem is that some platforms (e.g. Ardunio) doesn't provide much control over the build settings. 

> but that's currently broken...

What is broken exactly? You can pass `-DLV_LVGL_H_INCLUDE_SIMPLE` and adjust the include path with make or CMake.

**Comment by higaski** [comment]
> In most of the cases I assume `lvgl` and `lv_demos` are next each other.

Using CMake to perform a source build by directly fetching the repository from GitHub places the code inside a subdirectory of the build folder. So by default the layout looks like this:
```
[build folder]/_deps/lvgl-src
[build folder]/_deps/lv_demos-src
```

And so on.

> The problem is that some platforms (e.g. Ardunio) doesn't provide much control over the build settings.

And that's alright, I'm sure we can find a layout which suits them all. One of the (few) things I actually like about CMake is it's "don't care" attitude towards folder layouts. Give me (as a user) a proper CMake file and I don't care how deeply nested your files are and how you get them... you can make a script read them from a magnetic tape drive in a russian submarine... CMake simply doesn't care.

> What is broken exactly? You can pass `-DLV_LVGL_H_INCLUDE_SIMPLE` and adjust the include path with make or CMake.

Actually no, you can't. Yes you can pass the preprocessor macro to CMake, but fiddling with a targets include path is neither intended not really supported. Again, this isn't really a problem for lvgl itself since it can rely on relative paths to find all its headers but lv_demos and lv_drivers can't. There currently is no way for lv_demos to know where lvgl.h can be found because 
1. lvgl isn't a dependency of lv_demos (speaking from a CMake perspective)
2. lvgl does not state its header location as one of its properties, so even if it would be a dependency lvgl.h still woudln't be available to lv_demos

**Comment by kisvegabor** [comment]
Okay, (I'm not a CMake expert) how it is usually handled? IMO it's a typical pattern that an organisation has main and some optional repos that should work together.

**Comment by higaski** [comment]
> Okay, (I'm not a CMake expert) how it is usually handled?  

The header location is a pretty... unique situation. :sweat_smile:
Strictly speaking the default location _lvgl/lvgl.h_ isn't even part of the repository. From CMakes perspective the folder _lvgl_ doesn't has to exist at all. So in case we want to keep the LV_LVGL_H_INCLUDE_SIMPLE definition for compatibility reasons with various other build systems the only sane way to handle it with CMake would be to default define it with an option in my opinion. This way we could use CMAKE_CURRENT_SOURCE_DIR to point to the root path of lvgl and _lvgl.h_ could  then be located by dependents.

Dependencies between targets are expressed by explicitly linking with them. Take a look at the [CMakeLists.txt](https://github.com/boostorg/program_options/blob/0a1e54ba900adf7ab9d5de2b06fa04bf0e2f39f4/CMakeLists.txt#L27) file of Boost::program_options for example. They have multiple PUBLIC (external headers included in header files) and some PRIVATE (external headers included in source files) dependencies.

```CMake
target_link_libraries(boost_program_options
  PUBLIC
    Boost::any
    Boost::config
    Boost::core
    Boost::detail
    Boost::function
    Boost::iterator
    Boost::lexical_cast
    Boost::smart_ptr
    Boost::static_assert
    Boost::throw_exception
    Boost::type_traits
  PRIVATE
    Boost::bind
    Boost::tokenizer
)
```

Please consider that this is a very basic CMake example and one most likely written by a developer. It basically says "please provide me with those targets, wherever and however you got them". That's also the beauty of it, you could fetch those from git, you could have them installed on your system, you could have a local copy inside your project and add a subdirectory, ... lots of options there.
I guess a package maintainer on the other hand would have sleepless nights over this. There are way fancier ways to express version compatibilities like "I'm not compatibly with anything under 8.1" or something like that... but how about we start with what Boost does?

Something simple like this would be sufficient at first:
```CMake
target_link_libraries(lv_drivers PUBLIC lvgl::lvgl)
```

At least until someone who knows more about CMakes trickery comes along... :wink:


> IMO it's a typical pattern that an organisation has main and some optional repos that should work together.

Yes I agree, see Boost example.


/edit
Disclaimer: It might be that lv_drivers and or lv_demos only has a PRIVATE dependency to lvgl, I haven't checked.

/edit
For future reference:
lvgl depends on: LV_LVGL_H_INCLUDE_SIMPLE, LV_CONF_INCLUDE_SIMPLE
lv_drivers depends on: LV_LVGL_H_INCLUDE_SIMPLE, LV_CONF_INCLUDE_SIMPLE
lv_demos depends on: LV_LVGL_H_INCLUDE_SIMPLE, LV_DEMO_CONF_INCLUDE_SIMPLE

/edit
I've just realized that there are LV_CONF_PATH and LV_DEMO_CONF_PATH definitions which can be uses to point to specific locations. This could be directly translated to CMake.

**Comment by kisvegabor** [comment]
I won't pretend that I understood all you wrote :smile: 
Can you tell some concrete suggestions that we should change in order to make lvgl easier to use with CMake?

**Comment by higaski** [comment]
Sure. 

Drop include_directories, it's bad practice.

Use target_include_directories like the ZEPHYR build does.

Include the root path so that lvgl.h can be found by using CMAKE_CURRENT_SOURCE_DIR.

Default define LV_LVGL_H_INCLUDE_SIMPLE publicly so that this definition gets propagated to dependents.

lv_drivers and lv_demos **are** dependents. They must link with lvgl. You can't build them without it. This means there must be an target_link_libraries(lv_drivers PUBLIC lvgl) somewhere in the lv_drivers CMakeLists.txt file.

I guess an option to define LV_CONF_PATH and LV_DEMO_CONF_PATH would be a good idea as well, but I've tried this the other day and it didn't work. IIRC there are still places where lv_conf.h gets directly included and the *_PATH define gets ignored. This is an issue because there isn't really a "good practice" way of adding include paths to external CMake targets. If I would include the lvgl target somehow I wouldn't have a good way of telling it where lv_conf.h can be found other than defining LV_CONF_PATH.

/edit
I'll give this another go on in the next couple of days. Trying to unify CMake for lvgl, lv_drivers and lv_demos and make them work together properly.

**Comment by kisvegabor** [comment]
> I'll give this another go on in the next couple of days. Trying to unify CMake for lvgl, lv_drivers and lv_demos and make them work together properly.

Great! Please, keep us updated.
