### ISSUE TITLE
JavaScript simulator problem on localhost

### ISSUE THREAD

**Issue by leidto** [kisvegabor/lvgl#2677]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
I have problem with the simulator itself. I did the complete build process but the simulator doesn't start properly on localhost.
I tried both of Linux and Windows but the error was the same.
I gave this error:

```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "imp.py", line 52, in importer
ImportError: module not found

MicroPython v1.17-771-g42009b6ee-dirty on 2021-10-16; JS with Emscripten
Type "help()" for more information.
```

### To Reproduce
I started with this note: (lvgl_javascript_v8 branch)
https://github.com/lvgl/lv_micropython/tree/lvgl_javascript_v8#javascript-port
The build was successfull.

This line is problematic:
_Run an HTTP server that serves files from the current directory, and then browse to /lvgl_editor.html on the HTTP Server._

I run a http server from the directory _(localhost/lvgl_editor.html)_, which redirects to _http://localhost/javascript/bundle_out/index.html_ but I give the error below.

Note: There were missing files. For example, I had to copy wasm_file_api.js from folder docs to bundle_out.

I'm a JavaScript developer. I'd like to run the dev server. I also did the following:
1. npm i
2. npm run dev
3. http-server ./ 
4. On browser: _localhost/lvgl_editor.html_

But it didn't work.

### Expected behavior
The simulator appears correctly. You can also edit the CSS and the dev server compiles without error.

### Screenshots or video
![error](https://user-images.githubusercontent.com/7906474/137577390-19defd5b-c823-4896-8ab2-3ad5da2b20fe.PNG)

**Comment by embeddedt** [comment]
The instructions for getting up and running with the simulator locally are somewhat out of date. I don't use the `npm run dev` method anymore as it was causing issues. Unfortunately I didn't think to document exactly what the problem was. Sorry that I can't be more helpful there.

Here are the steps I usually use for development.

To get started I run `npm install` and then `npm run clean` to build the workers for the editor, however, it seems that you got that part working as I see the editor in your screenshot.

Normally I then run `live-server` in the `javascript` folder itself.

```console
<root>/lv_micropython_new/ports/javascript$ live-server --port=8080
Serving "<root>/lv_micropython_new/ports/javascript" at http://127.0.0.1:8080
```

The local URL thus ends up being http://127.0.0.1:8080/bundle_out/index.html.

Every time you change `frontend.html` or a file in `frontend_src` you have to re-run `npm run bundle`.

The current organization of the folder and build system is definitely not the easiest to work with or the most useful, but it's doing the job for now. As you might be able to tell, the use of a bundler and ES modules was retrofitted in after the fact, hence the 600-line monolithic `frontend_src/main.js` file instead of proper separated components.

I do intend to eventually clean this up and make it a lot more conventional and readable. I will try to also restore the dev functionality at that point.

Hopefully all of that helps. Please let me know if it doesn't work.

**Comment by leidto** [comment]
@embeddedt  Thanks for your reply.

The `npm run clean` command deletes all files in folder bundle_out.
Previously I ran the `make` command which generated the wasm files in the bundle_out also.
I run the live-server, but these files are missing. (wasm and lvgl_mp.js)
So I copied back the files into the bundle_out folder and now it's working.

It was quite tricky.

Please let me know if you resolved the dev functionality.

**Comment by embeddedt** [comment]
You have to run `npm run clean`, followed by `make -j4` (or `npm run build:wasm`), followed by `npm run bundle`, in that order. Otherwise it does end up deleting all the files in `bundle_out` like you mentioned.

I will try to find some time to clean this up soon.

**Comment by leidto** [comment]
@embeddedt  Did you find the problem while running the developer server?

**Comment by embeddedt** [comment]
@leidto Unfortunately I haven't had time to look into this yet. I've pinned the issue so it won't be closed automatically.

**Comment by embeddedt** [comment]
This is (mostly) fixed now. Dev mode works, but it still won't automatically copy `lvgl.html` to `bundle_out` if you change it. I will need to look into that some other time, so I'll leave the issue open.

I've also updated the instructions about building the port to reflect its current state. [This](https://github.com/lvgl/lv_micropython/tree/lvgl_javascript_v8#hot-reloading-for-frontend-devs) is the new section on using the dev server.

Hope that helps!

Also, a heads-up: you will need to follow steps 5-7 of the setup process if you pull `lv_micropython` now, as I'm working on integrating FreeType & Rlottie, and the Makefile now expects them to be present.

**Comment by leidto** [comment]
Thank you @embeddedt! The hot reloading works like a charm! 🚀

**Comment by kisvegabor** [comment]
@leidto 
Feel free to close this issue if all the issues are solved.

**Comment by leidto** [comment]
Dev mode works fine but it doesn't copy the lvgl.html file automatically. This must be done before closing.

**Comment by embeddedt** [comment]
I've switched to using Webpack as the bundler instead of Parcel. Webpack now tracks the `lvgl.html` as well as the WASM files so the manual copying is not needed. It also runs its own HTML server so `npm run serve` is not needed anymore either.

The instructions have been updated, but as a summary: `npm run dev` starts the development server, and `npm run bundle` creates the final production version that can be served independently. Those are the only two commands you should need.

Of course, make sure to run `npm install` after pulling the changes. :wink:
