### ISSUE TITLE
Why ony keys KEY_ENTER only send all key events? 

### ISSUE THREAD

**Issue by steprun** [kisvegabor/lvgl#2709]
### Introduce the problem

Other keys only send LV_EVENT_KEY, but no pressed and released event. Could I know why we do this?

**Comment by kisvegabor** [comment]
It's because the ENTER key simulates a press on the button. I.e. if you select a button with TAB (or other keys) ENTER behaves as you have clicked it via touch pad.

---

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

**Comment by steprun** [comment]
> It's because the ENTER key simulates a press on the button. I.e. if you select a button with TAB (or other keys) ENTER behaves as you have clicked it via touch pad.
> 
> We use GitHub Issues for development-related discussions.
> 
> Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

If my device is a music player, one key's function is that click for next song and long press for volumn up. How can I handle it?

**Comment by kisvegabor** [comment]
I'd be happy to help, but please open a topic for you question in the Forum and link it here.

**Comment by steprun** [comment]
> I'd be happy to help, but please open a topic for you question in the Forum and link it here.

https://forum.lvgl.io/t/multi-function-key-handle/7115
