### ISSUE TITLE
LV_COLOR_16_SWAP for two displays with different controllers in the same project.

### ISSUE THREAD

**Issue by SinglWolf** [kisvegabor/lvgl#2737]
The question is of practical importance.
There are two displays with different controllers.
The first display needs LV_COLOR_16_SWAP = 0.
The second display needs LV_COLOR_16_SWAP = 1.
How to change LV_COLOR_16_SWAP for two displays with different controllers in the same project?

**Comment by embeddedt** [comment]
As far as I know, it's not possible to configure LVGL this way. You would have to do the swapping for one of them yourself in its `flush_cb`.

**Comment by SinglWolf** [comment]
> As far as I know, it's not possible to configure LVGL this way.

But what about the declared features?
![2021-10-28_06-40-35](https://user-images.githubusercontent.com/32172969/139171844-0476023e-5600-435b-9d56-99c8d54f7488.png)

It turns out discrepancy.

As far as I know, there are very few controllers with a screen resolution of more than `320x240` pixels with support for 16-bit color for the `SPI` bus. I found only one, and even then I strongly doubt that he has this mode.
All displays I have found support `16-bit` color in parallel mode only.
And for the `SPI` bus there is only an `18-bit` color.
The `ESP32` driver team has released drivers that convert `18-bit` color to `16-bit` on the fly.
Drivers deliver artifacts to the display.
Very slow.
They require memory allocation in `DMA`, which `ESP32` lacks anyway.
And the use of displays with parallel data transmission with `ESP32` is not rational. Almost all pins will be busy serving the display.
There is a way out of this situation, but I doubt that you, I mean the development team, will take this step.
It is necessary to implement support for `18-bit` color at the level of the library core.
Then, indeed, the `LVGL` library can rightfully be called for embedded devices.
Do I have any hope that You will hear me, and not be dismissed as an annoying fly, as usual?
Believe my word, there are a lot of `ESP32` users who dream of a beautiful, user-friendly graphical interface for relatively large color displays with a resolution of 480x320 pixels, but I'm not the only one.
Would the introduction of full support for `18-bit` color at the library core level greatly damage your image and popularity?
Quite the opposite, it will only add reputation.

> You would have to do the swapping for one of them yourself in its `flush_cb`.

Can You get me some practical advice on how to implement this?

**Comment by JojoS62** [comment]
The limitation about color depth with multiple displays is documented:
https://docs.lvgl.io/master/overview/display.html#multiple-display-support
And it is says also that different depth need to be handled in the flush method.

With SPI, it is possible to handle 16 Bit parallel and SPI, and do it for an ILI9341 (parallel) and GC9A01 or ST7735 with 16 Bit SPI. Setting is no swap, the 'trick' is to use 16 bit SPI to use same byte order for SPI displays. This is also faster because only half of the registers are neccessary. Currently, I switch to 8 bit for the set window command and 16 bit for data. But it should be also possible to use set window also with 16 bit. The controllers have a nop command for padding the odd number of bytes in the set window command.

18 bit is a very odd number, memory efficient packing would consume a lot of CPU power. The closest would be to use full 32 bit color and reduce the transferred data to the display in the flush method. But this is also a time consuming step. Higher resolutions or color depth require simply more appropriate controllers.

**Comment by SinglWolf** [comment]
> With SPI, it is possible to handle 16 Bit parallel and SPI, and do it for an ILI9341 (parallel) and GC9A01 or ST7735 with 16 Bit SPI. Setting is no swap, the 'trick' is to use 16 bit SPI to use same byte order for SPI displays. This is also faster because only half of the registers are neccessary. Currently, I switch to 8 bit for the set window command and 16 bit for data. But it should be also possible to use set window also with 16 bit. The controllers have a nop command for padding the odd number of bytes in the set window command.

I, as a simple user, hardly distinguishing `MISO` from `MOSI`, understood everything.
And what, they said smart words, poked into the documentation, but did not reveal the essence of the issue.
If I had knowledge at the level of a display driver developer, I would not even come to you with stupid questions.
This means that `18-bit` color will not be supported.
Thanks for the answer.

**Comment by kisvegabor** [comment]
I agree that supporting 18-bit format would be great, because at least it saves some memory (3 bytes/pixel instead of 4 bytes/pixel). But I agree with @JojoS62 too, it could be slow. In fact you pay for the oddly packed structure more times than converting in flush_cb, because as lvgl draws the layers of the UI many pixels are drawn multiple times. While in the flush_cb only the final color needs to be converted. 

If we supported 18 bit format we could support 24 bit format too. Which is also unfortunate because it requires structs with 3 byte size. But low level embedded systems usually don't use the alpha channel in 32 bit color format. 

I added this to my todo list. Let's get back to this when we start to plan the next release (in a few weeks).

**Comment by SinglWolf** [comment]
> If we supported 18 bit format we could support 24 bit format too. Which is also unfortunate because it requires structs with 3 byte size. But low level embedded systems usually don't use the alpha channel in 32 bit color format.

I am wondering what the developers of display controllers were guided by, including only 18-bit color for the SPI bus?


> I added this to my todo list. Let's get back to this when we start to plan the next release (in a few weeks).

OK.

**Comment by kisvegabor** [comment]
> I am wondering what the developers of display controllers were guided by, including only 18-bit color for the SPI bus?

I don't know either... :slightly_frowning_face:

**Comment by SinglWolf** [comment]
> But I agree with @JojoS62 too, it could be slow.

Do you know what the slow driver is for the `ILI9488`, `ILI9486`, `LI9481` controller with the conversion of `18-bit` color to `16-bit`?
Obviously not.
Not only does the driver need to additionally allocate memory to `DMA` for color conversion, [artifacts appear on the display in the form of a series of pixels located at the end of each object](https://github.com/lvgl/lvgl_esp32_drivers/issues/116).
In addition, the information on the display screen is updated so slowly that, for example, the colon in the clock (font size `140` px.) Does not blink, but pours from one point to another.
But in the driver for the `ILI9341` controller, the speed is quite acceptable. If the support for `18-bit` color at the level of the library kernel would at least bring the speed of updating information on the display closer to the level of driver `ILI9341`, it would be great.

**Comment by embeddedt** [comment]
You might save memory with 18-bit support within LVGL, but I'm pretty sure the performance impact would be unacceptable.

Are the pixels packed, e.g. 18 bits for one pixel immediately followed by the next 18 bits, or are they still each aligned to 24-bit boundaries? I assume it's the former, otherwise the display controller may as well just support 24-bit color. That would mean even further complications in the implementation, as right now we can iterate over `lv_color_t`s using `for` loops. This becomes impossible if colors are not multiples of a byte size. Instead, we would have to keep track of a bit offset and manually extract and put together bits from several different addresses. This is inevitably going to be slower than the current approach of using nicely-aligned colors internally.

(I hope that explanation isn't too confusing.)

I highly doubt any sort of support for this within LVGL would improve performance at all. It would be better to find a faster way of doing the conversion. I haven't checked how it's being done right now, but it may be possible to gain some speed by converting only part of the buffer and starting to DMA that portion while the rest is being converted?

Another, possibly cheaper option is simply to use hardware that doesn't have this problem.

**Comment by kisvegabor** [comment]
> Are the pixels packed, e.g. 18 bits for one pixel immediately followed by the next 18 bits, or are they still each aligned to 24-bit boundaries?

Fortunately, aligned to 24 bit. 
![image](https://user-images.githubusercontent.com/7599318/139298460-13e215ae-5245-4976-8429-f3b0eff4554b.png)

See [here](http://www.lcdwiki.com/res/MSP3520/ILI9488%20Data%20Sheet.pdf) page 122.

**Comment by SinglWolf** [comment]
> Another, possibly cheaper option is simply to use hardware that doesn't have this problem.

I would be glad to hear your options such equipment.

**Comment by JojoS62** [comment]
It looks like only the ILI9488 has no 16 Bit RGB support, and there was already a long discussion in https://github.com/lvgl/lvgl_esp32_drivers/issues/1#issuecomment-656324082

But it seems the conversion from 32->18 bit was not merged. This conversion was already proposed to avoid the frequent memory allocations.

This discussion also don't follow the issues title about swapping 16 bit colors, 18/24 bit support is something completely different.

**Comment by kisvegabor** [comment]
> I would be glad to hear your options such equipment.

ILI9341 is very similar but supports RGB565 format

**Comment by SinglWolf** [comment]
> It looks like only the ILI9488 has no 16 Bit RGB support

ILI9486 also does not support `16-bit` color for the `SPI` bus. In addition, it has a 5-volt logic. I almost burned my `ESP32-S2`.

**Comment by JojoS62** [comment]
https://github.com/lvgl/lvgl_esp32_drivers/blob/b674d2d4f1192ae5744a2c50d701b4a2f82b2aa0/lvgl_tft/ili9486.c#L99-L126

there is no conversion

**Comment by SinglWolf** [comment]
> ILI9341 is very similar but supports RGB565 format

It has a resolution of 320x240 pixels.
I want to use a display with a resolution of 480x320 and higher.

**Comment by SinglWolf** [comment]
> https://github.com/lvgl/lvgl_esp32_drivers/blob/b674d2d4f1192ae5744a2c50d701b4a2f82b2aa0/lvgl_tft/ili9486.c#L99-L126
> 
> there is no conversion

This driver does not work absolutely, checked!

**Comment by SinglWolf** [comment]
ILI9486 works with the driver from ILI9488, only with different initialization. 18-bit color.

**Comment by SinglWolf** [comment]
> there is no conversion

I also believed these words and bought it.

**Comment by SinglWolf** [comment]
> https://github.com/lvgl/lvgl_esp32_drivers/blob/b674d2d4f1192ae5744a2c50d701b4a2f82b2aa0/lvgl_tft/ili9486.c#L99-L126
> 
> there is no conversion

https://github.com/lvgl/lvgl_esp32_drivers/issues/134

**Comment by SinglWolf** [comment]
> there is no conversion

https://github.com/lvgl/lvgl_esp32_drivers/issues/133

**Comment by SinglWolf** [comment]
Now you understand how urgent the problem is, I hope.

**Comment by JojoS62** [comment]
its true, with SPI the ILI9486 can display only RGB 1-1-1 or 6-6-6. You have opened an issue, thats ok. Your impatience not. I'm out.

**Comment by SinglWolf** [comment]
I look forward to the developers' activity.

**Comment by kisvegabor** [comment]
I've added 18/24 bit support to the roadmap of v8.2. There will be a dedicated issue/PR for. 

Until it's implemented the colors need to be converted. :slightly_frowning_face:

**Comment by SinglWolf** [comment]
> I've added 18/24 bit support to the roadmap of v8.2. There will be a dedicated issue/PR for.
> 
> Until it's implemented the colors need to be converted. 🙁

OK.
