### ISSUE TITLE
shadow doesn't work on btn when set theme dark true

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [kisvegabor/lvgl#2876]
### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
When I set theme with dark true as below:
lv_theme_default_init(NULL, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), 1, LV_FONT_DEFAULT);
the shadow doesn't work for btn.
but when I mark the code setting theme with dart true, it works.

**Comment by kisvegabor** [comment]
See here: https://github.com/lvgl/lvgl/blob/a5058eafd04a85f9fd691154a7cc2202a0f5b076/src/extra/themes/default/lv_theme_default.c#L283-L288

So it's missing intentionally. The reason is that it's difficult to use [shadows in dark themes](https://blog.prototypr.io/8-tips-for-perfect-dark-theme-ui-5aa34784784e). 

Regardless of it, you can add shadows manually.
