### ISSUE TITLE
Change canvas in JavaScript simulator

### ISSUE THREAD

**Issue by leidto** [kisvegabor/lvgl#3125]
### Introduce the problem
I'm working on a JavaScript application. My goal is to change the simulator's original canvas to another without reinitialize everything.
Unfortunately, it doesn't work as I expected. When I replace the original canvas, only the first interaction will paint on the other canvas and the events won't "copy". 

### Examples and cases
I run the above code on document.ondblclick (testing)
`var otherCanvas= document.getElementById('otherCanvas');`
`Module.canvas = otherCanvas`
`Module.ctx = otherCanvas.getContext('2d')`
`Module['createContext'](otherCanvas, false, true);`

I checked the micropython.js file but it's 10000 lines long so it's hard to read.

Do you have any idea to resolve this? Or has a specific code in the micropython.js to run?

### Video
[https://files.fm/u/vpgy5ranu](https://files.fm/u/vpgy5ranu)

**Comment by kisvegabor** [comment]
I think the root of the issue is that the SDL window is related to the first canvas and thus the mouse events are listened from there.

Maybe the simplest solution would be to have a different mouse driver with an interface like 
`lv.mouse_set_coords(x, y, presse/released)`. 
Any if the active canvas is clicked this function is called form JS. LVGL only needs to save the x, y and state values in global variables and return them from the `indev_read_cb`.

The other approach would be to tell SDL to replace the window by an other or so. Or at least the mouse get the events from the other window.  It's even hard to phrase what should happen.
