### ISSUE TITLE
glitch LCD Display

### ISSUE THREAD

**Issue by huynhphucloi** [kisvegabor/lvgl#3339]
hi there. i have problem register display. i config it
`    static lv_disp_draw_buf_t draw_buf_dsc_1;
    static lv_color_t buf_1[320 * 10];                          
    lv_disp_draw_buf_init(&draw_buf_dsc_1, buf_1, NULL, 320 * 10);   

    static lv_disp_drv_t disp_drv;                    
    lv_disp_drv_init(&disp_drv);                    

    disp_drv.hor_res = 320;
    disp_drv.ver_res = 240;`

but it glitch output as same as
![5bd04cf08c354d6b1424](https://user-images.githubusercontent.com/64252151/167231224-a62cfad7-a21e-44c6-8cad-c501f022cb33.jpg)
please help me! thanks

**Comment by embeddedt** [comment]
Were you able to solve this or did you close it by accident?

**Comment by huynhphucloi** [comment]
Nobody help it. I close it

**Comment by embeddedt** [comment]
That might be related to the fact that you posted it on the issue tracker instead of on the [forum](https://forum.lvgl.io/), and officially the issue tracker shouldn't be used for questions like this. If you post it on the forum and link to it here, I can try to take a look. Please be sure to include your `flush_cb` implementation as that is likely where the bug is.

**Comment by huynhphucloi** [comment]
Okay. I will try it again
