### ISSUE TITLE
How does lv_label implement LV_LABEL_LONG_DOT that does not match word

### ISSUE THREAD

**Issue by FASTSHIFT** [kisvegabor/lvgl#3426]
### Introduce the problem
The current `lv_label` will match the word for the replacement of `...`,as the picture shows:
![image](https://user-images.githubusercontent.com/26767803/175607537-f9cac7ed-04b4-462b-b28e-c34938f28b10.png)

I hope that without word matching, the characters at the end are`...`, such as `hello wor...`.
How should I do it?

### Examples and cases
```c
void label_test(void)
{
  lv_obj_t* label = lv_label_create(lv_scr_act());
  lv_obj_set_style_border_color(label, lv_color_black(), 0);
  lv_obj_set_style_border_width(label, 1, 0);
  lv_obj_set_size(label, 80, 20);
  lv_obj_center(label);
  lv_label_set_long_mode(label, LV_LABEL_LONG_DOT);
  lv_label_set_text(label, "hello world!");
}
```

### Suggested solution

**Comment by FASTSHIFT** [comment]
I try to crop the text myself, here is my code:
```c
void lv_label_set_text_ex(lv_obj_t* label, const char* txt, lv_coord_t txt_limit)
{
    lv_label_set_text(label, txt);

    const lv_font_t* font = lv_obj_get_style_text_font(label, LV_PART_MAIN);
    lv_coord_t letter_space = lv_obj_get_style_text_letter_space(label, LV_PART_MAIN);
    uint32_t txt_len = (uint32_t)strlen(txt);
    lv_coord_t txt_width = lv_txt_get_width(txt, txt_len, font, letter_space, LV_TEXT_FLAG_EXPAND);

    if (txt_width <= txt_limit)
    {
        LV_LOG_USER("No need to limit text length");
        return;
    }

    lv_coord_t dot_width_sum = lv_font_get_glyph_width(font, '.', '.') * 3;

    lv_point_t point;
    point.x = txt_limit - dot_width_sum;
    point.y = 0;
    uint32_t letter_pos = lv_label_get_letter_on(label, &point);

    lv_label_cut_text(label, letter_pos, UINT32_MAX);
    lv_label_ins_text(label, letter_pos, "...");
}

void labe_clip_test(void)
{
    lv_obj_t* label = lv_label_create(lv_scr_act());
    lv_obj_set_size(label, 100, 20);
    lv_obj_center(label);
    lv_obj_set_style_outline_width(label, 1, 0);
    lv_obj_set_style_outline_color(label, lv_color_black(), 0);
    lv_obj_set_style_outline_opa(label, LV_OPA_COVER, 0);
    
    lv_label_set_long_mode(label, LV_LABEL_LONG_CLIP);
    lv_label_set_text_ex(label, "12345 abdcefghi", 100);
}
```
![image](https://user-images.githubusercontent.com/26767803/175890436-e8dfe9b7-02e8-4225-ae45-0ec12e81c96e.png)

**Comment by kisvegabor** [comment]
The issue here is that "word" doesn't fit into the set width, so LVGL wraps it into next line. Therefore LVGL thinks that last character in the first line is "o" from "hello" and writes three dots after it. 

Something similar to your method could work, but we DOTS should work with multiline texts (with `\n` or word wrapping too). 

It's clear that there are a few things to reconsider with "long modes" (starting with the name "long mode" :smile: )
E.g. #3420

I think we should have a clear specification about what we want to achieve to redesign this part in v9. What I see now:

**What to do horizontally?**
- width is set to `LV_SIZE_CONTENT`
    - nothing, as the label will fit to the text size, it cannot  be scrolled, wrapped, dotted, etc
- width is set to `px`
    - wrap
    - scroll animation 
    - make it scrollable with scrollbars 
    - crop  
    - dots? but what if there is a multi line text? always keep only the first line? 

**What to do vertically?**
- height is set to `LV_SIZE_CONTENT`
    - nothing, as the label will fit to the text size, it cannot  be scrolled, wrapped, dotted, etc
- height is set to `px` 
   - scroll animation 
   - make it scrollable with scrollbars
   - crop
   - dots (at beginning, center, or end)
 
Both width and height should handle `min/max-width/height`


I can image different modes horizontally and vertically. E.g. dots if there are to many lines but make the text auto scroll horizontally. 

But maybe it's overkill. What do you think? 

cc @Akery

**Comment by W-Mai** [comment]
The `Text` component in iOS has such a method - lineLimit, which can limit the number of displayed lines of the current text component. If the limited number of lines is reached, the automatic line wrapping mechanism of the last line of text will have no effect.

If you limit the line to 2. like
> apple pen
> hello world

will display like

> apple pen
> hello wor...

but lvgl now will display like

> apple pen
> hello...

https://developer.apple.com/documentation/swiftui/text/

**Comment by kisvegabor** [comment]
Yeah, we should do something similar. I'm considering to introduce a new unit type like `em` on the web. (1 em means 1 row of text size).

This we could write: `lv_obj_set_height(label, LV_EM(3))`

**Comment by pprasa** [comment]
> ```c
> lv_label_set_text_ex
> ```

Thank you so much for this. I had lots of trouble with using dots to clip the long text and was not working for me. I could use this function to do the job. Thank you again.
