### ISSUE TITLE
scroll_ throw_Vect cannot converge to 0 when vect is negative

### ISSUE THREAD

**Issue by qinshijing** [kisvegabor/lvgl#3431]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When scroll_ throw_vect is -1, the following calculation will always be -1 and cannot converge to 0

    proc->types.pointer.scroll_throw_vect.x = (proc->types.pointer.scroll_throw_vect.x * 4) >> 3;
    proc->types.pointer.scroll_throw_vect.y = (proc->types.pointer.scroll_throw_vect.y * 4) >> 3;

    proc->types.pointer.scroll_throw_vect.x += (proc->types.pointer.vect.x * 4) >> 3;
    proc->types.pointer.scroll_throw_vect.y += (proc->types.pointer.vect.y * 4) >> 3;

### Expected behavior

Expect it to converge to 0

**Comment by kisvegabor** [comment]
It can really cause issues as the low pass filter works incorrectly with `vect.x = -1`. If the vector is continuously `-1`, `scroll_throw_vect.x` will be `-1`, `-2`, `-3`, `-4`, etc.

 For `vect.x = 1` it will be `0`, `0`, `0`, `0`, etc.


What we are doing now is 
```c
scroll_throw_vect = scroll_throw_vect / 2 + vect / 2
```

Which can be simplified to:
```c
scroll_throw_vect = (scroll_throw_vect + vect) / 2
```

`>> 1` instead of `/2` would produce `-1` from `-1 + 0` so it seems we can't avoid division here (without using a bunch of `if`s)

So what do you think about simplifying to:
```c
proc->types.pointer.scroll_throw_vect.x = (proc->types.pointer.scroll_throw_vect.x + proc->types.pointer.vect.x) / 2;
proc->types.pointer.scroll_throw_vect.y = (proc->types.pointer.scroll_throw_vect.y + proc->types.pointer.vect.y) / 2;
```

**Comment by qinshijing** [comment]
Yeah, I didn't think of a better way than division.

**Comment by kisvegabor** [comment]
I pushed the fix.
