### ISSUE TITLE
Faulty spinbox decrement algorithm

### ISSUE THREAD

**Issue by MYaqoobEmbedded** [kisvegabor/lvgl#3559]
https://github.com/lvgl/lvgl/blob/e19410f8f8a256609da72cff549598e0df6fa4cf/src/extra/widgets/spinbox/lv_spinbox.c#L302

The spinbox decrement algorithm special case fails with the following scenario:
- Set Range (-11 to 12)
- Change cursor position of spinbox to 10 (step = 10)
- When decrementing from 02 by 10, we get -12, which exceeds the low range (we should get -11, the algorithm clearly fails)

I am not sure what to suggest as a fix right now, I am working on a fix for my own code, I will let you know when I fix it.

**Comment by C47D** [comment]
I'll try to set a test case for this behavior. Is the expected behavior the correct one @kisvegabor @embeddedt?

**Comment by kisvegabor** [comment]
It seems the problem is that 02-10=-8 but we expect it to be -12. It happens only at zero crossing, so at first look bringing [this line](https://github.com/lvgl/lvgl/blob/e19410f8f8a256609da72cff549598e0df6fa4cf/src/extra/widgets/spinbox/lv_spinbox.c#L302) to line 299 can solve the issue.This way we immediately assume that 02 is -02 and can decrement properly. Probably some checks are still required at the beginning to no invert the value if subtraction would cause out of limits

What do you think?

>  Is the expected behavior the correct one @kisvegabor @embeddedt?

Yes, it is.

**Comment by C47D** [comment]
> It seems the problem is that 02-10=-8 but we expect it to be -12.

I think the expected value is -11 instead of -12, some sort of truncation when the calculated value is 'more negative' than the min range value.

> When decrementing from 02 by 10, we get -12, which exceeds the low range (we should get -11, the algorithm clearly fails)

@MYaqoobEmbedded when saying decrementing from 02 by 10 do you mean decrementing the spinbox twice while being in the decimal position? I tried to replicate the scenario with the test and I'm getting the expected -11 value. If it's only decremented once then the value should be -8 (2 - 10) instead of -12 or -11.

**Comment by MYaqoobEmbedded** [comment]
Hi,
Sorry, meant to say when decrementing from -2 by 10 once, I get -12, which is wrong because by min limit is -11.

**Comment by MYaqoobEmbedded** [comment]
![image](https://user-images.githubusercontent.com/53120926/184846467-b01c1d6f-51a2-4010-bb4a-16e7fa669ddc.png)

**Comment by MYaqoobEmbedded** [comment]
Moving this
`    /*Special mode when zero crossing*/
    if((spinbox->value - spinbox->step) < 0 && spinbox->value > 0) spinbox->value = -spinbox->value;`
to line 299 in spinbox source file fixes this condition, as [kisvegabor](https://github.com/kisvegabor) suggested earlier

**Comment by MYaqoobEmbedded** [comment]
[kisvegabor](https://github.com/kisvegabor) suggestion to move the zero crossing code to line 299 will not solve the issue, because still 2 - 10 = -8, not -11 that this change will produce.
I will spend sometime reviewing your spinbox algorithm when I have a spare time and will write you back. no worries guys, and keep up the good work.

**Comment by kisvegabor** [comment]
I've pushed a fix to https://github.com/lvgl/lvgl/tree/fix/spinbox-range-violation

Please take a look

**Comment by embeddedt** [comment]
@kisvegabor Maybe I missed something but that branch appears to just be a copy of `master` at the moment. Did the push fail?

**Comment by kisvegabor** [comment]
Ah, true. Updated.

**Comment by MYaqoobEmbedded** [comment]
Great, I will test it on my project

**Comment by kisvegabor** [comment]
It's already fixed and merged so I close this issue. Let me know if you have any remarks.
