### ISSUE TITLE
Resolution Defines are Absent from Config Template

### ISSUE THREAD

**Issue by hhaudio** [kisvegabor/lvgl#3655]
Hi, I am getting set up with LVGL, and all the tutorials I'm finding tell me to set up the following defines to work with my display.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/37379609/188199794-0ec57ce1-fa5f-422e-bf31-c5beb11207ba.png">

"In the config file comments explain the meaning of the options. Check at least these three configuration options and modify them according to your hardware:

LV_HOR_RES_MAX Your display's horizontal resolution.
LV_VER_RES_MAX Your display's vertical resolution.
LV_COLOR_DEPTH 8 for (RG332), 16 for (RGB565) or 32 for (RGB888 and ARGB8888)."

However, these resolution defines are absent from the config template provided on this repo. This seems to directly contradict the documentation you provide here: https://docs.lvgl.io/latest/en/html/porting/project.html#. Can you please clarify what's happening here and how the project should be ported?

**Comment by embeddedt** [comment]
Welcome to LVGL!

The documentation you are referencing is for v7; the latest documentation can be found here: https://docs.lvgl.io/master/porting/project.html

In v8 there is no longer a need to set the resolution macros.

(`latest` being in the URL is a technical limitation since we had linked to v7 documentation through that URL in many places.)

----------------------
We use GitHub issues for development-related discussions.
Please use the [forum](https://forum.lvgl.io/) to ask questions.
