### ISSUE TITLE
Dedicated LVGL Arduino drivers

### ISSUE THREAD

**Issue by codewitch-honey-crisis** [kisvegabor/lvgl#3679]
### Is it desirable to have dedicated arduino drivers for LVGL?

LVGL currently uses TFT_eSPI to do the last mile graphics ops under arduino - for actually getting the pixels the display

### Examples and cases

TFT_eSPI is great, but it's a bit heavy handed when you're only using a little bit of it for LVGL.

Furthermore, it doesn't support SSD1306 over I2C for example, nor most (if any) e-paper displays.

Also, as far as I know, TFT_eSPI does not support capacitive touch.

### Suggested solution
I am the author of [htcw_gfx](https://honeythecodewitch.com/gfx) which is yet another graphics library - one that I wrote to serve my professional pursuits since I needed certain features like truetype and I needed it to be responsive to change when i needed feature adds.

I've since decided to roll things like its TrueType support into LVGL, but I also have a ton of drivers for it that I already wrote and could easily be ported to work with LVGL.

I also have touch drivers separated off, both for the most common SPI resistive touch, and the common I2C capacitive touch controllers.

I can port these to LVGL pretty easily, but is it worth it? Would it be worthwhile enough to say, update Squareline studio with additional options, for example? I'm just trying to draw a bead here.

**Comment by kisvegabor** [comment]
One of our goal for v9 is to have the drivers right in lvgl. I've already started to develop its architecture here: https://github.com/lvgl/lvgl/tree/arch/drivers

In [this comment](https://github.com/lvgl/lvgl/issues/2720#issuecomment-1112515857) I explained the concept. 

It'd be great if you were interested in adding new drivers because
1. we tested the architecture
2. we had drivers :slightly_smiling_face:
