### ISSUE TITLE
Refactor CMSIS pack

### ISSUE THREAD

**Issue by bbkarim** [kisvegabor/lvgl#3857]
### Introduce the problem
We need to make the LVGL CMSIS pack compliant with Open-CMSIS-Pack rules (https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/cp_Packs.html#pack_Cclass)

- LVGL is a Variant (Bundle) of the Graphics Class but not a class.
- Graphics Classes should be implemented thru Bundles.
- All files inside the pack should be added to the PDSC file, including header files and documentation.
- Conditions need to reviewed.
- GPU support should be done via variants, and they should be exclusive.
- Port files need to be implemented as templates.
- lv_conf_cmsis.h need to reviewed for better include of the RTE_Components.h.
- Examples have to be properly implemented also inside the PDSC.
- All component's versions need to reviewed and defined.

### Examples and cases
The goal is to be able to enable the LVGL Graphics software pack and build its examples.

### Suggested solution
Initial draft is available from https://github.com/lvgl/lvgl/pull/3820

**Comment by kisvegabor** [comment]
cc @GorgonMeducer

**Comment by GorgonMeducer** [comment]
> LVGL is a Variant (Bundle) of the Graphics Class but not a class.
> Graphics Classes should be implemented thru Bundles.

Those are recommendations, not mandates. As LVGL cmsis-pack has already been added to KEIL.com, the current structure is already approved by Arm. For backward compatibility and better identification. I think no need to change existing solutions. 

<img width="752" alt="image" src="https://user-images.githubusercontent.com/13148491/206828457-a91b813e-f808-4ee3-87e3-284b2b7a0c3e.png">


@kisvegabor, what's your opinion?  

Please see the RTE snapshot below:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/13148491/206828513-09878b90-9d92-42e7-8267-0339f799f32a.png">

If we put LVGL inside the `Graphics`, then people won't be able to find LVGL until they click the drop list (here you can see MDK-Plus and MDK pro).

For the current solution, LVGL could be seen at the top level of the RTE table. Arm has no problem with this. Hence I see no problem in keeping LVGL at the top level. As I mentioned, `Graphics` is just a recommended category for people to put their graphic stacks in, which is not mandatory. 


@bbkarim I am sorry, I would reject this change. We are not starting from scratch, the existing LVGL cmsis-packs have been created and maintained for one year. A lot of customers are using it. NXP even demonstrate the LVGL cmsis-pack to their customers.  We should not make this structural change to gain trivial things.

**Comment by GorgonMeducer** [comment]
> All files inside the pack should be added to the PDSC file, including header files and documentation.

That's one thing we could improve.  But please note this is also a recommendation, and it depends on how a library handles the folder structures. For LVGL's method, I think most of the header files don't need to be added. 

@kisvegabor  can you please put some commends about this?

Please create a dedicated PR for just this without changing other parts.

**Comment by GorgonMeducer** [comment]
> Conditions need to review.

We need a dedicated issue for this.

**Comment by GorgonMeducer** [comment]
> GPU support should be done via variants, and they should be exclusive.

Please create a dedicated PR for just this.

I agree that GPU support should be exclusive from each other, but each GPU support could have its variants. For example, Arm-2D GPU will have multiple variants soon to support different configurations, e.g.

- Arm-2D SW (Helium) only
- Arm-2D DMA350
- Arm-2D Arm Customized Instruction
- etc.

Due to this, I prefer to keep the current structure (each GPU support has a dedicated sub-class) and use conditions for mutual-exclusive.

**Comment by GorgonMeducer** [comment]
> Port files need to be implemented as templates.

Please create a dedicated PR for just this.

**Comment by GorgonMeducer** [comment]
> lv_conf_cmsis.h need to reviewed for better include of the RTE_Components.h.

We need dedicated issues to discuss this, not here. Please identify the problem you observed. For each problem, please create a dedicated issue.

**Comment by GorgonMeducer** [comment]
> Examples have to be properly implemented also inside the PDSC.

Good idea. Please create a dedicated PR for just this.

**Comment by GorgonMeducer** [comment]
> All component's versions need to reviewed and defined.

Sound like a big project, I am just not sure where should we identify those versions.

**Comment by bbkarim** [comment]
@GorgonMeducer thank you very much for your inputs. My understanding is that LVGL is not class to add it at the same level with other real classes like Graphics, Network and Device. It was just confusing for me, but if you say that it is something intended to be like that and you agreed on it, then it is fine unless a user will select another Graphics variant in addition to LVGL. How do you plan to manage such situation? Also other classes would need to know maybe that a 'Graphics' class is enabled in the solution so they can add some extras... Do they need to check for LVGL but not Graphics ?

**Comment by GorgonMeducer** [comment]
>How do you plan to manage such a situation? 

It allows people to add more than one Graphic library. I see no problem at all. 
As you have already pointed out, if LVGL is set to be a bundle, then people who use LVGL cannot use other GUI stacks under the same `Graphics` class.  This is a problem.

Maybe @kisvegabor can put some comments on this. As far as I know, LVGL is open and friendly, it provides an option for customers to choose from.  LVGL doesn't have the attitude that "IF YOU CHOOSE LVGL, YOU CANNOT USE OTHER GUI". 

If LVGL doesn't have such an attitude, why on earth the LVGL cmsis-pack chooses bundle and pose such a fact to users?

There could be only one RTOS in an embedded software system. Still, you surely can use different GUIs for different screens for various reasons, for example, to reuse existing application code (under different GUI stacks).


> Do they need to check for LVGL but not Graphics?

Usually, checking the existence of the `Graphics` class has no practice meaning. If possible, would you mind naming any situation where people have to check the `Graphics` and do something accordingly? I bet you can name some, but can you also ensure they are the usual conditions? (i.e. 80% of people will use those situations in daily development)

> Do they need to check for LVGL

Checking the LVGL is more meaningful than checking the Graphics. Because people who use LVGL to develop applications need to know the existence of LVGL. There is no Generic GUI application which can be used across different GUI libraries. All the API and GUI Designers are different. 


>My understanding is that LVGL is not class

As you can see, different people have different understandings. My understanding is that `class` can be anything, and pack creators have the freedom to introduce their classes.

Existing classes are recommendations, not mandatory. See here:

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/13148491/206899157-c594efe8-653a-4b82-8d0d-c399b72fe1f0.png">

It says "try to map...". It is not a "must" or "should".

Also, please check here:

<img width="984" alt="image" src="https://user-images.githubusercontent.com/13148491/206899392-0223a76f-c95d-4d81-83df-689781e44cf2.png">

That implies a lot of people might create their own `class` and hence open-cmsis-pack organization provides a way for people to suggest a new `standardized class`.  Of course, not all user-defined new classes can be standardized, which means the number of non-standard user classes is way more than the newly added standard `classes`. 

And also, some of the cmsis-packs can fall into the same or similar `class`, but they are not mutually exclusive. Hence, you can expect a lot of non-standard classes and non-bundle components under user-defined classes.

**Comment by kisvegabor** [comment]
>  For LVGL's method, I think most of the header files don't need to be added.

Only `lvgl.h` needs to be included.

> As far as I know, LVGL is open and friendly, it provides an option for customers to choose from. LVGL doesn't have the attitude that "IF YOU CHOOSE LVGL, YOU CANNOT USE OTHER GUI".

LVGL is a library, not a framework. E.g. as can use 2 FFT libraries at the same, you can use LVGL with other GUI libs too. And actually it can happen in the practice too. E.g. LVGL has a [GTK driver](https://github.com/lvgl/lv_drivers/tree/master/gtkdrv), so GTK and LVGL needs to live together.  To give a more embedded-like example: If your system has 2 displays you can use an other lib for a small monochrome display, and LVGL for a TFT.


>> My understanding is that LVGL is not class

> As you can see, different people have different understandings. My understanding is that class can be anything, and pack creators have the freedom to introduce their classes.

These are my thoughts:
- If there is no strong reason to break backward compatibility, then don't break backward-compatibility.
- If ARM and Keil say it's ok if LVGL is class, then it should be fine
- LVGL is more then a simple lib (like an FFT lib) but less than a framework (e.g. QT). I can imagine more modules,  plugins, or bindings related to LVGL.  Then we can add these in the class and consider the class as an umbrella for the "LVGL ecosystem".

**Comment by GorgonMeducer** [comment]
I can give you another example of non-standard classes:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/13148491/206963342-8b21f91f-df3a-4dd8-be92-91fae86e99a1.png">

Here TencentOS Tiny is an RTOS from [Tecent](https://www.tencent.com/en-us/)

`TencentOS Tiny` is used as a class, the same as LVGL. 

PikaScript is an ultra-small Python VM. (There is no such class for script language or VM)

**Comment by kisvegabor** [comment]
@bbkarim 
Just to see things clearer: am I correct to assume that the root of the "class-issue" is that you are planning to add UI libs supported by ST as CMSIS-Packs (I don't know just guessing), and you would like to see all libs in one common place? Or your view is purely technical?

**Comment by bbkarim** [comment]
> @bbkarim Just to see things clearer: am I correct to assume that the root of the "class-issue" is that you are planning to add UI libs supported by ST as CMSIS-Packs (I don't know just guessing), and you would like to see all libs in one common place? Or your view is purely technical?

@kisvegabor 
My view is purely technical. Wasn't expecting a variant of 'well known class' like Graphics to be exposed as a new class by itself. But thanks to you and @GorgonMeducer I can understand more now your vision. Even if I think that the provided GTK example is not enough because it is more for another build environment for linux but not cmsis-pack (AFAIK) but the problem of having two Graphical stacks in the same application is still ambiguous for such class definition.
So I agree, hopefully you have green light to do it, so let's continue that.
Originally, I had two goals with this thread:
1. Run LVGL on STM32 NUCLEO boards equipped with basic display boards, using the X-NUCLEO-GFX01M2 and X-NUCLEO-GFX01Z1 expansion boards.
2. Achieve that using:
  - STM32CubeMX with LVGL CMSIS pack + X-CUBE-DISPLAY expansion software pack
  - Keil with LVGL + X-CUBE-DISPLAY CMSIS packs

**Comment by kisvegabor** [comment]
Great that we are on the same page now :relaxed: 

Finally what issues left?

**Comment by bbkarim** [comment]
> Great that we are on the same page now ☺️
> 
> Finally what issues left?

**Comment by bbkarim** [comment]
@kisvegabor I'm re-opening this becasue I was thinking that all suggests was already implemented with 1.12.0 version.
Remaining patches are: 
    arch(cmsis-pack): refactoring cmsis-pack
      * Reworked components to get more granulated sub-groups
      * Renamed LVGL-Essential into LVGL-CORE Clean-up its files
      * Add missing hearder files
      * Add more widgets and demos
    arch(lv_conf): update lv_conf.h and KConfig files for the new cmsis-pack
    arch(lvgl): add the new lv_layouts.h header file
    arch(lvgl): include only needed header files
    feat(gpu): add support for STM32U5xx devices
      * Added STM32U5 compilation flag
      * restrict Cache maintenance code to Cortex M7 devices
    fix(hal): remove extra include of "../draw/sdl/lv_draw_sdl.h"
      * remove compilation warnings too
    fix(scripts): in lv_conf_internal preserve newline value for updated file

I'll push the new branch including all of that.

**Comment by GorgonMeducer** [comment]
@bbkarim please generate PRs one by one. Thank you very much.

In my opinion, the top priority should be the support for STM32U5.

**Comment by GorgonMeducer** [comment]
> arch(cmsis-pack): refactoring cmsis-pack
> * Reworked components to get more granulated sub-groups
> * Renamed LVGL-Essential into LVGL-CORE Clean-up its files
> * Add missing hearder files
> * Add more widgets and demos

For this part, please keep the original LVGL::lvgl structure and add an additional one called: LVGL::lvgl9.

This LVGL::lvgl9 will employ the new structure you proposed, and the existing users can use the old LVGL::lvgl for backward compatibility - we will mark its version as deprecated.

**Comment by bbkarim** [comment]
I'm also implementing a draft script to check content of the PDSC files/defines in regards of repo files and lv_conf_cmsis.h content.
The script will of course support ignored files/defines to allow exceptions.
The proposed script will be as I said a first draft, but up to you to keep it or enhance it.

**Comment by bbkarim** [comment]
> > arch(cmsis-pack): refactoring cmsis-pack
> > 
> > * Reworked components to get more granulated sub-groups
> > * Renamed LVGL-Essential into LVGL-CORE Clean-up its files
> > * Add missing hearder files
> > * Add more widgets and demos
> 
> For this part, please keep the original LVGL::lvgl structure and add an additional one called: LVGL::lvgl9.
> 
> This LVGL::lvgl9 will employ the new structure you proposed, and the existing users can use the old LVGL::lvgl for backward compatibility - we will mark its version as deprecated.

Hello @GorgonMeducer,
This mean a complete new cmsis pack no more related to LVGL.lvgl !
I had tried this and found that all dependencies will need to be reworked to target only LVGL.lvgl9 but not LVGL.lvgl.
Also, releases section will be clean-up and we will start again from v1.0.0 ...
Can't we found a better way to ensure backward compatibility and so keep the same LVGL.lvgl cmsis pack ?
Did you tried to open an old project generated with 1.12.0 and migrate it to 1.13.0-alpha ? Did you expect a lot of broken things ?
Sorry I don't know how to test that... Should I use Keil ? which project can I try with ??

Finally I think moving from **LVGL.lvgl** to **LVGL.lvgl9** is a big decision that need more analysis...

Thanks in advance,
Karim

**Comment by GorgonMeducer** [comment]
> > > arch(cmsis-pack): refactoring cmsis-pack
> 
> > > 
> 
> > > * Reworked components to get more granulated sub-groups
> 
> > > * Renamed LVGL-Essential into LVGL-CORE Clean-up its files
> 
> > > * Add missing hearder files
> 
> > > * Add more widgets and demos
> 
> > 
> 
> > For this part, please keep the original LVGL::lvgl structure and add an additional one called: LVGL::lvgl9.
> 
> > 
> 
> > This LVGL::lvgl9 will employ the new structure you proposed, and the existing users can use the old LVGL::lvgl for backward compatibility - we will mark its version as deprecated.
> 
> 
> 
> Hello @GorgonMeducer,
> 
> This mean a complete new cmsis pack no more related to LVGL.lvgl !
> 
> I had tried this and found that all dependencies will need to be reworked to target only LVGL.lvgl9 but not LVGL.lvgl.
> 
> Also, releases section will be clean-up and we will start again from v1.0.0 ...
> 
> Can't we found a better way to ensure backward compatibility and so keep the same LVGL.lvgl cmsis pack ?
> 
> Did you tried to open an old project generated with 1.12.0 and migrate it to 1.13.0-alpha ? Did you expect a lot of broken things ?
> 
> Sorry I don't know how to test that... Should I use Keil ? which project can I try with ??
> 
> 
> 
> Finally I think moving from **LVGL.lvgl** to **LVGL.lvgl9** is a big decision that need more analysis...
> 
> 
> 
> Thanks in advance,
> 
> Karim

Looks like you don't know what I said. If you don't mind, you can leave this work to me. 

Would you mind working on the support for STM32U5 first? Thank you very much.

**Comment by bbkarim** [comment]
Changes are now available from #3920

@GorgonMeducer, it will be nice if you explain more what I've missed from your last message about the LVGL::lvgl structure and how do you plan to fork the two pack version.

Thanks in advance,
Karim

**Comment by GorgonMeducer** [comment]
> Changes are now available from #3920
> 

As I mentioned before, please separate those changes into dedicated PR. 

What you have done will block this Big PR for really a long time because a lot of changes need to be discussed first. 

Many of your changes has no dependency, hence separate them is the good manner. 

![image](https://user-images.githubusercontent.com/13148491/212293468-0b8415b4-d208-4bc8-9ba3-0f7ba06d1031.jpeg)

For example, feat(gpu): add support for STM32U5xx devices and fix(scripts): in lv_conf_internal preserve newline value for updated have no dependency. 

As listed above, only two patches are related to cmsis-pack others are about different topics. 

Please create dedicated PRs for those individual patches. 

PLEASE do NOT mix patches about different topics into one PR.

**Comment by GorgonMeducer** [comment]
> @GorgonMeducer, it will be nice if you explain more what I've missed from your last message about the LVGL::lvgl structure and how do you plan to fork the two pack version.
> 

![image](https://user-images.githubusercontent.com/13148491/212298791-69167f2b-e9e1-4ed1-aced-7f56127fc13c.jpeg)

As shown above, in current version of pdsc file, we have a bundle called 'LVGL::lvgl'

What I suggested was that in this pdsc file: 

a. Keep the existing bundle (we will put a 'deprecated' in its Cversion field and the description. 
b. Add a new bundle called LVGL::lvgl9

With this method, we can have backwards compatibility for existing users (they can still the old bundle, we might maintain the old bundle for half year or so. This buys people time to move to the new bundle). 

New users can use the new LVGL::lvgl9 bundle. We can have a version number starting from v1.1.0 after the corresponding PR is accepted. 

Since We are using bundles, so old one and the new one are mutual exclusive from each other. 

In the future, when we have LVGL10-dev we will do the following work, i.e. 

1. rename LVGL::lvgl9 to LVGL::lvgl10 
2. Remove old LVGL::lvgl (if it hasn't been removed yet)

I hope this is clear. 

Please create and only create a dedicated PR just for this structural change. 

Please do NOT mix the pack-cheching script and GPU support into this PR. 

THANK YOU FOR YOUR COOPERATION.

**Comment by GorgonMeducer** [comment]
We can close this as there are dedicated PR for topics discussed here.
