### ISSUE TITLE
Where is LV_COLOR_16_SWAP in 9.0.0 dev version ?

### ISSUE THREAD

**Issue by baldhead69** [kisvegabor/lvgl#3935]
Hi,

I did not find LV_COLOR_16_SWAP in lv_conf.h.

Need i set this in driver init ?
if yes, how ?

I want 16 bits color and not swapped.

Thank`s.

**Comment by kisvegabor** [comment]
You can set `disp_drv.color_format = LV_COLOR_FORMAT_NATIVE_REVERSE`.

Note that `master` is still heavily under development and it's recommended to use `release/v8.3`.

**Comment by hyansuper** [comment]
Hi,
I am using GC9A01 TFT display.
Setting `LV_COLOR_FORMAT_NATIVE_REVERSE` or `LV_COLOR_FORMAT_NATIVE_ALPHA_REVERSED` has no effect.

I understand v9.0 is still in dev but willing to try because it fixed some bugs in v8.3

---
edit: `lv_disp_set_color_format(disp_drv, LV_COLOR_FORMAT_NATIVE_REVERSED);`

**Comment by kisvegabor** [comment]
Hi,

It's working for me. Did you set LV_COLOR_DEPTH to 16?

**Comment by yunshanghen** [comment]
It is possible to enable     lv_draw_sw_rgb565_swap(px_map, lv_area_get_size(&offset_area)); to solve problems such as color inversion.
