### ISSUE TITLE
can't hide border for rotated button

### ISSUE THREAD

**Issue by hyansuper** [kisvegabor/lvgl#4273]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

I created a round button, it has 0 border and shadow, and same color as bg. but when the buttons is roated 45 deg, I can see an outline.

### To Reproduce
You can put below code into online python simulator https://sim.lvgl.io/v9.0/micropython/ports/javascript/
```python

import display_driver
import lvgl as lv

scr = lv.obj()

btn = lv.btn(scr)
btn.set_size(50,50)
btn.set_style_radius(lv.RADIUS_CIRCLE,0)
btn.set_style_transform_angle(450,0)
btn.set_style_shadow_width(0,0)
btn.set_style_border_width(0,0)
btn.align(lv.ALIGN.CENTER, 0, 0)
label = lv.label(btn)
label.set_text('B')

scr.set_style_bg_color(btn.get_style_bg_color(0), 0)
lv.scr_load(scr)
```

### Expected behavior
No outline
### Screenshots or video
![image](https://github.com/lvgl/lvgl/assets/44317361/c044b581-2ea3-40ae-942f-f9a03dc4f133)

**Comment by kisvegabor** [comment]
I've just tested it and it's a really tricky issue. The problem is that on the corners where button is transparent it's black with 0 opacity and LVGL mixes that black color. 

In the `feat/parallel-rendering` branch it work better but we still need a few weeks to merge that branch.

As workaround you can do this `btn.set_style_bg_opa(0,0)`
