### ISSUE TITLE
Is background-size considered to be supported?

### ISSUE THREAD

**Issue by C-Ackerman** [kisvegabor/lvgl#4642]
Hi Gabor:
  Have you considered supporting background-size?

https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

**Comment by kisvegabor** [comment]
Hey, 

I've just opened #4648 to discuss some related questions.

**Comment by bjsylvia** [comment]
@kisvegabor  There are also [`background-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position) and [`background-repeat`](url) related to the background. Maybe we should think about them together?

**Comment by kisvegabor** [comment]
This issue is also related: https://github.com/lvgl/lvgl/issues/4102

I think we can unify what settings we have for `lv_image` and the background. I'm thinking about making the background a new `LV_PART_BACKGROUND` so we would have all the x, y, width, height, align, image recolor, etc style options.

**Comment by kisvegabor** [comment]
Closing in favor of #4733.
