### ISSUE TITLE
unaligned memory access

### ISSUE THREAD

**Issue by chimeiw** [kisvegabor/lvgl#4747]
When I use lvgl8.3.5 and port it to my embedded platform, after running for a while, the memory usage is only 16%, the screen freezes and prompts:

usage fault
Unaligned memory access

**Comment by kisvegabor** [comment]
Please enable all asserts in lv_conf.h `LV_USE_ASSERT_...`

**Comment by KentLee86** [comment]
I think I've narrowed down the root cause for this class of "unaligned memory access" hardfaults on 32-bit ARM (mostly reported with STM32H7 + external SDRAM). Opened #10015 with a one-line fix.

### Root cause

On Cortex-M3 / M4 / M7 / M33 (ARMv7-M, ARMv7E-M, ARMv8-M) the `LDRD` / `STRD` instructions require strict 8-byte alignment and fault with a UsageFault (`UFSR.UNALIGNED`) **regardless of `CCR.UNALIGN_TRP`**. GCC happily emits them for 64-bit struct accesses because it assumes `malloc` returns pointers aligned to `alignof(max_align_t) = 8` (due to `double` / `long long`).

The built-in TLSF allocator currently picks `ALIGN_SIZE_LOG2 = 2` (4 bytes) on all 32-bit builds. Internal SRAM usually gets away with it because allocations happen to land on 8-byte boundaries; **external RAM pools** configured through `LV_MEM_ADR` don't, and the first non-trivial allocation from the draw path hardfaults.

### Evidence

Reproducer: STM32H743II + 32 MB FMC SDRAM, `LV_MEM_ADR = 0xC0100000`, 800×480 RGB565 dashboard. GDB after fault:

```
CFSR  = 0x01000000
  UFSR = 0x0100   → bit 8 = UNALIGNED
HFSR  = 0x40000000 (FORCED)

lv_draw_rect → lv_malloc_core → lv_tlsf_malloc(tlsf=0xC0100000)
```

Ruled out first:
- SDRAM / FMC / MPU are fine — direct mixed-struct R/W and a 25 MB concurrent pattern stress run with 0 errors.
- `CCR.UNALIGN_TRP` is already 0; clearing it explicitly doesn't help (LDRD's strict alignment is ISA-level).
- Reproduced on 9.2.2 and 9.3.0.

### Workaround (without the fix)

Build LVGL with `-mno-unaligned-access` so GCC stops emitting LDRD/STRD. Clears the symptom but leaves TLSF under-aligned relative to `alignof(max_align_t)` on these targets.

### Real fix

#10015 promotes `ALIGN_SIZE_LOG2` to 3 on `__ARM_ARCH >= 7 && !__ARM_ARCH_6M__`. No behavior change on AVR / RV32 / ARMv6-M, `TLSF_64BIT` still takes precedence.

Given there's a concrete reproducer, a clear root cause and a minimal fix, could this issue be reopened? Happy to provide the SDRAM reproducer project if useful.
