### ISSUE TITLE
newest version break! lv_global.disp_refresh->buf_act is nullptr!!!!

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#5206]
### LVGL version

v9.0.0

### What happened?

when i run the lv_demo_widgets ,break! 2024.01.06
![图片](https://github.com/lvgl/lvgl/assets/40679769/c261882e-1a7e-457e-b3d6-d0c494fca21d)

### How to reproduce?

newest, run the lv_demo_widgets 
![图片](https://github.com/lvgl/lvgl/assets/40679769/c261882e-1a7e-457e-b3d6-d0c494fca21d)

**Comment by kisvegabor** [comment]
Hi,

Have you updated LVGL to the latest version in the project?

Please confirm if you are using this project: https://github.com/lvgl/lv_port_pc_visual_studio If so @MouriNaruto could you take a look at this issue?

**Comment by xinsuinizhuan** [comment]
> Hi,
> 
> Have you updated LVGL to the latest version in the project?
> 
> Please confirm if you are using this project: https://github.com/lvgl/lv_port_pc_visual_studio If so @MouriNaruto could you take a look at this issue?

the  latest version, 2024.01.04 version is ok， but the version of 2024.01.05 start break.

**Comment by PGNetHun** [comment]
Maybe this is the problem:
1 line is missing from the new code:
https://github.com/lvgl/lvgl/commit/304a3c35736178ce19e36f8cbd0dcd197a232a58#diff-d5e5e7b4b434f724deeead3491cc6d37ecc20b0db8f61600d528bcdd73353ebfL397

![image](https://github.com/lvgl/lvgl/assets/25751703/7a9edb9e-7b11-42df-bf0b-63c40e140063)

**BUT:**
XuNeo has alread a PR to fix this:
https://github.com/lvgl/lvgl/pull/5204/files#diff-d5e5e7b4b434f724deeead3491cc6d37ecc20b0db8f61600d528bcdd73353ebfR396

**Comment by kisvegabor** [comment]
And do you use the our visual studio project as it is?

**Comment by MouriNaruto** [comment]
![image](https://github.com/lvgl/lvgl/assets/10867563/2272026b-aa6b-42e6-8b9e-8401514542eb)

I have found the same issue when I using the latest LVGL implementation.

Kenji Mouri

**Comment by MouriNaruto** [comment]
It looks https://github.com/lvgl/lvgl/commit/304a3c35736178ce19e36f8cbd0dcd197a232a58 break the Windows platform implementation.

![image](https://github.com/lvgl/lvgl/assets/10867563/facc76a7-33f9-48c4-84ca-25ac9d9bcdc6)

I think LVGL should check the pointer of disp_refr->buf_act.

Windows platform won't set the buffer at the beginning because the Window size needs to be determined after the sizing fixing. (For example, in simulator mode, we need to ensure the content size is the same as the user set for that with considering the zoom. Also, I don't want to create the buffer we actually unused.)

Kenji Mouri

**Comment by MouriNaruto** [comment]
![image](https://github.com/lvgl/lvgl/assets/10867563/bd95294c-5507-4aae-ac76-aa5ee138235b)

I tried to do a simple fix and looks OK. I think maybe LVGL guys have a better way to do that.

Kenji Mouri

**Comment by kisvegabor** [comment]
Thank you for looking into it. Please review #5210.
