### ISSUE TITLE
Out of memory assert if LV_SDL_RENDER_MODE is LV_DISPLAY_RENDER_MODE_DIRECT

### ISSUE THREAD

**Issue by rmshub** [kisvegabor/lvgl#5270]
### Introduce the problem

Observed following error when LV_SDL_RENDER_MODE is LV_DISPLAY_RENDER_MODE_DIRECT and screen is black.
`[Error] (0.348, +348)    lv_draw_buf_create: Asserted at expression: buf != NULL (Out of memory) lv_draw_buf.c:174`

The following settings are used in lv_conf.h and display size is 1024 x 600
```
#define LV_SDL_BUF_COUNT       2    /*1 or 2*/
#define LV_MEM_SIZE (6U * 1024U * 1024U)          /*[bytes]*/
```

**Comment by kisvegabor** [comment]
@XuNeo Earlier I used normal `malloc` to allocate the buffers in order to avoid this out of memory issue. (I assume for SDL there is enough memory and draw buffers shouldn't allocated from LVGL's memory pool),

I think we should either use `lv_draw_buf_init()` with `malloc`ed buffer or revert these changes as recommended [here](https://github.com/lvgl/lvgl/pull/5204).
