### ISSUE TITLE
Improve the animation API 

### ISSUE THREAD

**Issue by kisvegabor** [kisvegabor/lvgl#5350]
### Introduce the problem

> This is feature is the pioneer of the [new shaping-pitching](https://docs.lvgl.io/master/CONTRIBUTING.html) project management process. Please, leave your feedback about how effective you find this method, so that we can improve it. 
In this issue we can discuss what we want or don't want to add to this feature. Based on that we will create a [pitch](https://github.com/lvgl/lvgl/blob/pitches/__pitch_template.md) and someone can start the development considering the set boundaries.

As described in #4920 the "create" API of animations doesn't follow the other modules as we have `lv_anim_init` instead of `lv_anim_create`. Without the `create` function the life cycle management of the animations is much harder.

### Proposal

For backward compatibility we should keep the current `init` API too and `lv_anim_create` can set a flag to tell if the animation was malloc-ed in it.

Besides the animations are lacking some more controls too:
- pause
- restart
- seek to time
- auto delete on ready

The idea of "open-ended" animations  also came up. It means we specify from where to start, a speed, and the speed changes according to the animation path. The main issue I see with it is it depends on how often the animation handler is called (as we can move the object in the animation handler without knowing any absolute values). For this we can rather have a helper which calculates the start/end values from some special input parameters. But it's not critical for now.

Of course tests, and examples needs to added and documentation needs to be updated as well.

**Comment by hyansuper** [comment]
minor problem: `ready_cb` sounds like "ready to start" but actually it's called when anim finishes, `complete_cb` maybe more appropriate

**Comment by kisvegabor** [comment]
> minor problem: ready_cb sounds like "ready to start" but actually it's called when anim finishes, complete_cb maybe more appropriate

It was mentioned by others as well.  I've opened a #5378 for renaming ready_cb to completed_cb

**Comment by ggoraa** [comment]
By the way, I had an idea of an "animation library" for LVGL in the back of my head for several weeks by now, basically something with keyframes, orchestration of different animations together, etc

**Comment by kisvegabor** [comment]
Do you mean something like the [Timeline animation](https://docs.lvgl.io/master/overview/animations.html#timeline)?

**Comment by ggoraa** [comment]
Hot damn, I didn't realise LVGL already had allat

**Comment by kisvegabor** [comment]
Not stale

**Comment by kisvegabor** [comment]
cc @XuNeo

**Comment by kdschlosser** [comment]
One thing I would like to note. Animations should not be held to the same timer that the refresh is handled under. In all honesty I am not even sure why there is a refresh timer. If something needs to be refreshed then it should be when lv_tack_handler gets called regardless of any timer But when an animation is running milliseconds can me the difference between it running smoothly or not and that refresh timer could toss a wrench into the mix.

There should also be a way to allow the user to specify if the animation is to continually run from start to finish with no interruptions. It would also be nice if animations were thread safe. What I mean by that is using an OS they could have the animation running as a startup splash screen at the same time the UI could be loading. The UI would get set to a blank or empty object as to not interfere with the animation that was running. The UI could load into that empty object which the splash screen animation was playing.

I am not sure if LVGL is decoupled in a manner that would allow that to be done or not. I know that right now when `lv_obj_create(NULL)` is called the returned pointer is automatically attached to the default display. If there was a way to not do this. leave it in limbo until the user actually sets the object to a display.

For some reason I think that this kind of a thing could be done without too much difficulty. The reason I say this is because no 2 objects would be getting changed at the same time. That would be due to the "screen" not being attached to a display. The only common point between say a running animation and the screen that is having the UI elements loaded is going to be the display. If it's not attached to the display there would be no common connection between the 2.

**Comment by kisvegabor** [comment]
> If something needs to be refreshed then it should be when lv_tack_handler gets called regardless of any timer.

E.g. you can have `lv_timer`s running with 5ms period, but you might want to update the display only in each 50ms. 
Note that you can specify the refresh rate of the timer by getting the timer using `lv_display_get_refr_timer(display)`

> What I mean by that is using an OS they could have the animation running as a startup splash screen at the same time the UI could be loading.

It's doable, you can have a dedicated thread for `lv_timer_handler()` which protected by the mutex. You can also call `lv_refr_now(NULL)` at any time to request a UI refresh. 

It's very unlikely that we will make LVGL thread safe because it's way easier to handle on the application side.  

You can also have 2 screens: one for the splash, and another for the UI. When the splash screen is loaded LVGL does nothing with the other screen. So even if it's attached to the display object it doesn't bother much.

**Comment by becseya** [comment]
I'd be happy to help this ticket move toward a more specific implementation. To iterate on the ideas so far:

- __Adding `lv_anim_create`__: Alternative instead of "`lv_anim_t a;` + `lv_anim_init(&a);`". Requires a marker to be added to `lv_anim_t` to skip malloc-ing in `lv_anim_start()`.
   - Raises the issue of ownership. (User can free the pointer before the animation finishes, user will have a wild pointer after the animation finishes). Is this acceptable or should be addressed some way?
- __"auto delete on ready"__
   - Isn't this already implemented? Animations are feed upon completion. 
- __pause, restart, seek to time:__ These functionalities are similar to `lv_anim_timeline`.
   - Is the goal to achieve same functionality without re-allocation?
   - Should `lv_anim_timeline` be refactored to use the new calls?


As a site question: Where does the `Log out` button of the default "Widgets" demo get animated? I couldn't find it in the source

**Comment by kisvegabor** [comment]
Hey,

> I'd be happy to help this ticket move toward a more specific implementation.

Awesome! :+1: 

> Raises the issue of ownership. (User can free the pointer before the animation finishes, user will have a wild pointer after the animation finishes). Is this acceptable or should be addressed some way?

It's acceptable. It's the same as 
```c
lv_obj_t * label = lv_label_create(parent);
lv_free(label); //Not allowed
lv_obj_delete(label); //Do this
``` 
So as the animation was created with `lv_anim_create` it should be deleted with `lv_anim_delete`. After that `lv_anim_t *` will be really a wild pointer, however to use should handle that, as he/she made it a wile pointer. In the above example `label` will be a wild pointer after deleting it, which is okay.

> "auto delete on ready"
Isn't this already implemented? Animations are feed upon completion.

It's really being freed when `lv_anim_init` was used (as an internal `lv_anim_t` is allocated which freed in the end). However in case of `lv_anim_create` the user might want to handle the life cycle of the animation by manually deleting it.


>pause, restart, seek to time: These functionalities are similar to lv_anim_timeline.

Good observation! The timeline is really similar but for a group of animations. We should have a similar API for a single animation too. 

> Is the goal to achieve same functionality without re-allocation?

I think we can just add a `paused` flag to make `lv_anim_handler` skip that animation when it's paused. 

> Should lv_anim_timeline be refactored to use the new calls?

I need to take a deeper look at anim timeline to decide. Let's leave it to the end as a bonus. 

> Where does the Log out button of the default "Widgets" demo (or any other button) get animated? I couldn't find it in the source

It's coming from the [`grow` style](https://github.com/lvgl/lvgl/blob/master/src/themes/default/lv_theme_default.c#L395-L397) which is animated by a transition style (automatic animation on state change, just like in CSS) [here](https://github.com/lvgl/lvgl/blob/master/src/themes/default/lv_theme_default.c#L232-L242).

**Comment by becseya** [comment]
Ah okay. So when it's created by `lv_anim_create` the "internal free" should not be automatically applied, Unless the "auto delete on ready" is true.

API mechanism is also clear for pause, restart, seek to time.

Is there any extra step before stating implementation?

PS: Thanks for the info, I would not have find style mechanism in such a sort time,

**Comment by kisvegabor** [comment]
> Ah okay. So when it's created by lv_anim_create the "internal free" should not be automatically applied, Unless the "auto delete on ready" is true.

Yes, at least this how I imagined it. 

> Is there any extra step before stating implementation?

I can't think of any blocking issues. Feel free to start working on the implementation and we will see what comes up. :slightly_smiling_face:

**Comment by kisvegabor** [comment]
Still in progress in https://github.com/lvgl/lvgl/pull/6197

**Comment by kisvegabor** [comment]
Let continue in https://github.com/lvgl/lvgl/pull/6197
