### ISSUE TITLE
is v9 support label text recolor now？

### ISSUE THREAD

**Issue by NewObject404** [kisvegabor/lvgl#5428]
### LVGL version

v9.0.0

### What happened?

recoloring example not support.

**Comment by C47D** [comment]
From #4599

> For v9 It can be replaced by lv_span which has much more features.

**Comment by PGNetHun** [comment]
Related ticket: https://github.com/lvgl/lvgl/issues/5352

**Comment by NewObject404** [comment]
> From #4599
> 
> > For v9 It can be replaced by lv_span which has much more features.



> Related ticket: #5352

Thanks, this is a great solution.

**Comment by andyrea76** [comment]
the span is all well and good but you have to kinda know in advance surely then where all the spans are in your label ?  rather than the recolouring option which it totally dynamic to the string you pass in and you only have one object to have to look after / create for the label rather than n spans

**Comment by kisvegabor** [comment]
It's a very good point! 
In https://github.com/lvgl/lvgl/issues/6019 I've described an option for "Inline text processing" which could be basically the replacement of what we had in v8. What do you think about it? (Please reply in https://github.com/lvgl/lvgl/issues/6019 to keep the discussion more organized)
