### ISSUE TITLE
Add CI test for Windows build

### ISSUE THREAD

**Issue by kisvegabor** [kisvegabor/lvgl#5904]
### Introduce the problem

We have some warnings shown only [MSVC](https://github.com/lvgl/lvgl/pull/5873/files).

### Proposal

It's would be nice to set up a Window CI as well.

**Comment by kisvegabor** [comment]
Not stale

**Comment by liamHowatt** [comment]
I have opened a PR for building on Windows with GCC which supports `windows.h` and contains exceptions to the standard such as `_aligned_malloc` found in MSVC. #6015. This can be a starting point for using MSVC. It may be simple to use MSVC in CMake, but I do not know for certain, and wanted to establish some progress in the right direction in case MSVC is not trivial to use in CMake. `cl.exe` is the compiler that'd be invoked at each build step.

Since we just want to build for now, it might be simpler to maintain a build script (?) separate from CMake for MSVC.

**Comment by kisvegabor** [comment]
Great! Let's continue in the PR! :slightly_smiling_face:
