### ISSUE TITLE
[v9.1.0] canvas example 6 & 8 shows incorrect results?

### ISSUE THREAD

**Issue by BlynkGO** [kisvegabor/lvgl#5946]
### LVGL version

v9.1.0

### What happened?

![image](https://github.com/lvgl/lvgl/assets/65327357/5bf81b73-a008-4dea-b5f3-ec4e10c16245)

I have tried canvas examples 6 and 8, 
but I cannot display images and vectors.

How to solve this problem?
Thank you.

**Comment by liamHowatt** [comment]
Thanks @BlynkGO,

- The star image needs to be fixed. It will be fixed by this PR #5800
- `lv_canvas_finish_layer(canvas, &layer);` just needs to be added at the end. https://github.com/liamHowatt/lvgl/commit/1c80f9e6575132620c039a7c5fde9e2c9d539e2a I've been waiting to create a PR for it after the other one gets merged.

You can add the missing line at the end and the image will appear but it will be distorted. You can use a different image for now, or grab the fix from the PR.

**Comment by BlynkGO** [comment]
Thank you very much @liamHowatt 

`canvas example 6`  the canvas can display image now.
![image](https://github.com/lvgl/lvgl/assets/65327357/15100387-0efa-429d-a323-4fdba4316ba6)

and `canvas example 8` (canvas draw vector) still can't display anything

![image](https://github.com/lvgl/lvgl/assets/65327357/9bb0e2ff-a25e-47e6-ad94-0f3fabb69060)

How to solve the example 8 issue?

**Comment by liamHowatt** [comment]
Hey @BlynkGO, that example uses vector graphics. Make sure you have `LV_USE_VECTOR_GRAPHIC` set to `1` and have either `LV_USE_THORVG_INTERNAL` or `LV_USE_THORVG_EXTERNAL` set to `1` in your lv_conf.h.

For internal, make sure you compile and link the files in src/libs/thorvg. If you're using cmake, add `lvgl_thorvg` to your `target_link_libraries`

**Comment by BlynkGO** [comment]
Hi @liamHowatt 

Thanks for the reply.

Now I'm using on Platformio for simulation.

When I config  platformio.ini by the following addition.

```
build_flags = 
  -D LV_USE_VECTOR_GRAPHIC=1
  -D LV_USE_THORVG_INTERNAL=1
```

It occurs some compile error.

![image](https://github.com/lvgl/lvgl/assets/65327357/1c359ee0-e668-4257-925f-fad19f6fe93f)

I don't know how to link the files in src/libs/thorvg 
How to solve the issue?

**Comment by BlynkGO** [comment]
@liamHowatt 

Thank you very much. It's worked!!!
