### ISSUE TITLE
slow dynamic image refresh

### ISSUE THREAD

**Issue by cyberumut** [kisvegabor/lvgl#6034]
### Introduce the problem

when I go from page1 to page2 the background image loads very slowly my processor is esp32s3 I have a 7" screen.

I am loading the background image as .bin in rgb565 format 

Do you have any suggestions

**Comment by liamHowatt** [comment]
Hi @cyberumut,

Are you able to create a simple benchmark that compares the speed of LVGL loading the background image vs you sending the image from static buffer over the display interface without LVGL?

**Comment by Gabboide** [comment]
Hi, I have the same problem using Arduino Giga with the display shield. Everythings seems slowed down when a bin image is loaded.

**Comment by liamHowatt** [comment]
Are you loading it from a file? Or a C array?

**Comment by Gabboide** [comment]
Thanks for your answer Liam. I'm loading it from a bin file saved in the USB host connected to the Arduino GIGA. After the sketch is loaded, everything seems to work fine, but after a little time (usually around 1 minute) it won't show the image any more, instead there is a white background with "No data". This happens if I switch the background between an image and a simple colored background, but also if I use only the image as the background and switch only the graphical objects above it. I don't know if it's a memory issue or if it's linked to the USB management by Arduino. I'm linking you the code I used.

`//Libraries
#include <string.h>
#include "Arduino_USBHostMbed5.h"
#include "DigitalOut.h"
#include "FATFileSystem.h"
#include "Arduino_H7_Video.h"
#include "Arduino_GigaDisplayTouch.h"
#include "lvgl.h"

//Libraries initialization
Arduino_H7_Video          Display(800, 480, GigaDisplayShield);
Arduino_GigaDisplayTouch  TouchDetector;
USBHostMSD msd;
mbed::FATFileSystem usb("usb");

//Constants
const int DISPLAY_WIDTH = Display.width();
const int DISPLAY_HEIGHT = Display.height();
const long refreshIntervalMain = 20;

enum NAV {
  DASHBOARD = 1,  //1
  MENU            //2
  };

//Variables
bool isSerialAvailable = false;

unsigned long previousMillis = 0;

NAV currentNavIndex;
NAV newNavIndex;

static lv_obj_t * currentView = NULL;
static lv_obj_t * oldView = NULL;
static lv_obj_t * bootView = NULL;
static lv_obj_t * bootInfoLabel = NULL;
static lv_obj_t * dashboardBg = NULL;
static lv_obj_t * menuBg = NULL;

//Functions
//--------------------------------------------------------Arduino-------------------------------------------------------
void(* resetFunc) (void) = 0;//declare reset function at address 0
void rebootArduino() {
  resetFunc();
}
//----------------------------------------------------------------------------------------------------------------------

//--------------------------------------------------------Serial--------------------------------------------------------
template<typename T, typename U>
void printSerialMsg( T message, U modifier, bool newLine = false ){
  if(isSerialAvailable) {
    if (newLine) {
      Serial.println(message, modifier);
    } else {
      Serial.print(message, modifier);
    }
  }
}

template<typename T>
void printSerialMsg( T message, bool newLine = false ){
  if(isSerialAvailable) {
    if (newLine) {
      Serial.println(message);
    } else {
      Serial.print(message);
    }
  }
}

void updateLabelAndPrintMessage(lv_obj_t * obj, const char * text) {
  lv_label_set_text(obj, text);
  printSerialMsg(text, true);
}
//----------------------------------------------------------------------------------------------------------------------

//--------------------------------------------------------USB--------------------------------------------------------
void initializeUSBHost() {
  pinMode(PA_15, OUTPUT);  //enable the USB-A port
  digitalWrite(PA_15, HIGH);
  updateLabelAndPrintMessage(bootInfoLabel, "Starting USB driver...");
  lv_timer_handler();
  delay(1000);
  // if you are using a Max Carrier uncomment the following line
  // start_hub();

  while (!msd.connect()) {
    //while (!port.connected()) {
    delay(1000);
  }

  updateLabelAndPrintMessage(bootInfoLabel, "Mounting USB device... ");
  int err = usb.mount(&msd);
  if (err) {
    updateLabelAndPrintMessage(bootInfoLabel, "Error mounting USB device " + err);
    char * t1 = lv_label_get_text(bootInfoLabel);
    char * t2 = "\nMake sure USB device is connected and reboot";
    strcat(t1, t2);
    lv_label_set_text(bootInfoLabel, t1);
    showObject(lv_obj_get_child(bootView, 1)); //Show reboot button
    while (1)
      ;
  }
  lv_timer_handler();
  delay(1000);
}
//-------------------------------------------------------------------------------------------------------------------

//--------------------------------------------------------Navigation--------------------------------------------------------

static void navigateTo(NAV index) {
  newNavIndex = index;
}

static void navigation_handler() {
  if (newNavIndex != currentNavIndex) {
    oldView = currentView;
    switch (newNavIndex) {
      case DASHBOARD:
        currentView = createViewDashboard();
        break;
      case MENU:
        currentView = createViewMenu();
        break;
      default:
        break;
    }
    lv_obj_del(oldView);
    oldView = NULL;
    if (newNavIndex == DASHBOARD) {
      showObject(dashboardBg);
      hideObject(menuBg);
    } else if (currentNavIndex == DASHBOARD) {
      showObject(menuBg);
      hideObject(dashboardBg);
    }
    showObject(currentView);
    currentNavIndex = newNavIndex;
  }
}

static void hideObject(lv_obj_t * obj) {
  lv_obj_add_flag(obj, LV_OBJ_FLAG_HIDDEN);
}

static void showObject(lv_obj_t * obj) {
  lv_obj_clear_flag(obj, LV_OBJ_FLAG_HIDDEN);
}

//-------------------------------------------------BOOT VIEW---------------------------------------------
lv_obj_t* createBootView() {
  lv_obj_t * bgRect = lv_obj_create(lv_scr_act());
  lv_obj_set_style_bg_opa(bgRect, LV_OPA_COVER, LV_PART_MAIN);
  lv_obj_set_style_bg_color(bgRect, lv_color_make(0, 0, 0), LV_PART_MAIN);
  lv_obj_set_style_border_width(bgRect, 0, LV_PART_MAIN);
  lv_obj_set_style_radius(bgRect, 0, LV_PART_MAIN);
  lv_obj_set_size(bgRect, DISPLAY_WIDTH, DISPLAY_HEIGHT);
  lv_obj_align(bgRect, LV_ALIGN_CENTER, 0, 0);

  lv_obj_t * label = lv_label_create(bgRect); //0
  static lv_style_t labelStyle;
  lv_style_init (&labelStyle);
  lv_style_set_text_font(&labelStyle, &lv_font_montserrat_36);
  lv_style_set_text_color(&labelStyle, lv_color_make(255, 255, 255));
  lv_obj_add_style(label, &labelStyle, LV_PART_MAIN);
  lv_obj_center(label);

  lv_obj_t * btnReboot = (lv_obj_t*) lv_btn_create(bgRect); //1
  hideObject(btnReboot);
  lv_obj_set_size(btnReboot, 300, 120);
  lv_obj_center(btnReboot);
  lv_obj_set_style_bg_opa(btnReboot, LV_OPA_100, LV_PART_MAIN);
  lv_obj_add_event_cb(btnReboot, btn_event_cb_reboot, LV_EVENT_CLICKED, NULL);

  lv_obj_t * btnRebootLabel = lv_label_create(btnReboot);
  lv_label_set_text(btnRebootLabel, "Riavvia");
  static lv_style_t buttonLabel;
  lv_style_init (&buttonLabel);
  lv_style_set_text_font(&buttonLabel, &lv_font_montserrat_36);
  lv_obj_add_style(btnRebootLabel, &buttonLabel, 0);
  lv_obj_center(btnRebootLabel);

  return bgRect;
}

static void btn_event_cb_reboot(lv_event_t * e) {
  printSerialMsg("Riavvio in corso...", true);
  rebootArduino();
}
//-------------------------------------------------------------------------------------------------------

//-------------------------------------------------DASHBOARD VIEW---------------------------------------------
static void initDashboardBackground() {
  dashboardBg = lv_img_create(lv_scr_act());
  hideObject(dashboardBg);
  lv_img_set_src(dashboardBg, "F:/sfondi/dolphin.bin");
}

static lv_obj_t * createViewDashboard() {
  static lv_coord_t col_dsc[] = { 500, LV_GRID_TEMPLATE_LAST};
  static lv_coord_t row_dsc[] = { 400, LV_GRID_TEMPLATE_LAST};

  lv_obj_t * grid = lv_obj_create(lv_scr_act());
  hideObject(grid);

  lv_obj_set_grid_dsc_array(grid, col_dsc, row_dsc);

  lv_obj_set_size(grid, DISPLAY_WIDTH, DISPLAY_HEIGHT);

  lv_obj_center(grid);
  lv_obj_set_style_bg_opa(grid, LV_OPA_0, LV_PART_MAIN);
  lv_obj_set_style_border_opa(grid, LV_OPA_0, LV_PART_MAIN);

  lv_obj_t * label;
  lv_obj_t * obj;

  obj = lv_obj_create(grid);
  lv_obj_set_grid_cell(obj, LV_GRID_ALIGN_STRETCH, 0, 1,
                        LV_GRID_ALIGN_STRETCH, 0, 1);
  lv_obj_set_flex_flow(obj, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_style_bg_opa(obj, LV_OPA_0, LV_PART_MAIN);
  lv_obj_set_style_border_opa(obj, LV_OPA_0, LV_PART_MAIN);

  lv_obj_t * btn = (lv_obj_t*) lv_btn_create(grid);
  lv_obj_set_size(btn, 300, 120);
  lv_obj_center(btn);
  lv_obj_set_style_bg_opa(btn, LV_OPA_100, LV_PART_MAIN);
  lv_obj_add_event_cb(btn, btn_event_cb1, LV_EVENT_CLICKED, NULL);

  label = lv_label_create(btn);
  lv_label_set_text(label, "Menu!");
  static lv_style_t buttonLabel;
  lv_style_init (&buttonLabel);
  lv_style_set_text_font(&buttonLabel, &lv_font_montserrat_36);
  lv_obj_add_style(label, &buttonLabel, 0);
  lv_obj_center(label);

  return grid;
}

static void btn_event_cb1(lv_event_t * e) {
  printSerialMsg("Vai al menu", true);
  navigateTo(MENU);
}
//------------------------------------------------------------------------------------------------------------

//-------------------------------------------------MENU VIEW---------------------------------------------
static void initMenuBackground() {
  menuBg = lv_obj_create(lv_scr_act());
  hideObject(menuBg);

  static lv_style_t style;
  lv_style_init(&style);
  lv_style_set_radius(&style, 0);

  /*Make a gradient*/
  lv_style_set_bg_opa(&style, LV_OPA_COVER);
  lv_style_set_bg_color(&style, lv_color_make(0, 0, 50));
  lv_style_set_bg_grad_color(&style, lv_color_make(0, 0, 100));
  lv_style_set_bg_grad_dir(&style, LV_GRAD_DIR_VER);  
  lv_style_set_bg_dither_mode(&style, LV_DITHER_ORDERED);  
  lv_style_set_border_width(&style, 0);

  lv_obj_add_style(menuBg, &style, LV_PART_MAIN);
  lv_obj_set_size(menuBg, DISPLAY_WIDTH, DISPLAY_HEIGHT);
  lv_obj_align(menuBg, LV_ALIGN_CENTER, 0, 0);
}

static lv_obj_t * createViewMenu() {
  static lv_coord_t col_dsc[] = { 500, LV_GRID_TEMPLATE_LAST};
  static lv_coord_t row_dsc[] = { 400, LV_GRID_TEMPLATE_LAST};

  lv_obj_t * grid = lv_obj_create(lv_scr_act());
  hideObject(grid);

  lv_obj_set_grid_dsc_array(grid, col_dsc, row_dsc);

  lv_obj_set_size(grid, DISPLAY_WIDTH, DISPLAY_HEIGHT);

  lv_obj_center(grid);
  lv_obj_set_style_bg_opa(grid, LV_OPA_0, LV_PART_MAIN);
  lv_obj_set_style_border_opa(grid, LV_OPA_0, LV_PART_MAIN);

  lv_obj_t * label;
  lv_obj_t * obj;

  obj = lv_obj_create(grid);
  lv_obj_set_grid_cell(obj, LV_GRID_ALIGN_STRETCH, 0, 1,
                        LV_GRID_ALIGN_STRETCH, 0, 1);
  lv_obj_set_flex_flow(obj, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_style_bg_opa(obj, LV_OPA_0, LV_PART_MAIN);
  lv_obj_set_style_border_opa(obj, LV_OPA_0, LV_PART_MAIN);

  lv_obj_t * btn = (lv_obj_t*) lv_btn_create(grid);
  lv_obj_set_size(btn, 300, 120);
  lv_obj_center(btn);
  lv_obj_set_style_bg_opa(btn, LV_OPA_100, LV_PART_MAIN);
  lv_obj_add_event_cb(btn, btn_event_cb2, LV_EVENT_CLICKED, NULL);

  label = lv_label_create(btn);
  lv_label_set_text(label, "Dashboard!");
  static lv_style_t buttonLabel;
  lv_style_init (&buttonLabel);
  lv_style_set_text_font(&buttonLabel, &lv_font_montserrat_36);
  lv_obj_add_style(label, &buttonLabel, 0);
  lv_obj_center(label);

  return grid;
}

static void btn_event_cb2(lv_event_t * e) {
  printSerialMsg("Vai alla dashboard", true);
  navigateTo(DASHBOARD);
}
//-------------------------------------------------------------------------------------------------------

//--------------------------------------------------------------------------------------------------------------------------

void setup() {
  Serial.begin(115200);
  Display.begin();
  TouchDetector.begin();
  lv_init();

  bootView = createBootView();
  bootInfoLabel = lv_obj_get_child(bootView, 0);

  while (!Serial && millis() < 1000)
    ;

  isSerialAvailable = Serial;

  initializeUSBHost();

  initDashboardBackground();
  initMenuBackground();  

  currentView = createViewDashboard();
  
  showObject(dashboardBg);
  showObject(currentView);
  currentNavIndex = DASHBOARD;
  newNavIndex = DASHBOARD;

  lv_obj_del(bootView);
  bootView = NULL;
}

void loop() {
  unsigned long currentMillis = millis();

  if (abs(currentMillis - previousMillis) >= refreshIntervalMain) {
    previousMillis = currentMillis;
    navigation_handler();
    lv_timer_handler();
  }
}
`

**Comment by liamHowatt** [comment]
Thanks for all the details! I changed your code the minimum amount to be able to run in the simulator. I don't observe the image disappearing after 1 minute. Do you have `LV_USE_STDLIB_MALLOC` set to `LV_STDLIB_BUILTIN` in your lv_conf.h? Change it to `LV_STDLIB_CLIB` and use mbed_statistics again to watch for a memory leak. If it's already set to `LV_STDLIB_CLIB` and you don't see the memory increasing out of control, then I can suggest some other ideas.
