### ISSUE TITLE
close the frame, break!

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#6059]
### LVGL version

v9.1.1

### What happened?

in windows，when close the pop window，break:
![图片](https://github.com/lvgl/lvgl/assets/40679769/7a1b6a65-f096-4c1b-bb91-13bd278936d9)
because the disp_refr_timer is NULL in lv_sysmon.c

**Comment by xinsuinizhuan** [comment]
to add a judget:
![图片](https://github.com/lvgl/lvgl/assets/40679769/b18669c5-9377-4858-9ba2-85d9ace47315)

**Comment by liamHowatt** [comment]
Hi, your default display is not set for some reason. Did you create one? If so, did you use `lv_sdl_window_create` or `lv_windows_create_display`?

**Comment by liamHowatt** [comment]
Also, since you appear to have a debugging environment, could you please check to see if you reach this line and whether the returned timer is NULL?

https://github.com/lvgl/lvgl/blob/eb62ddf4ea8e84ea76cc89d932ce20f0066b8618/src/display/lv_display.c#L95

**Comment by xinsuinizhuan** [comment]
> Hi, your default display is not set for some reason. Did you create one? If so, did you use `lv_sdl_window_create` or `lv_windows_create_display`?

 i set #define LV_USE_OS   LV_OS_WINDOWS in lv_conf.h and i use lv_windows_create_display:
![图片](https://github.com/lvgl/lvgl/assets/40679769/a2afcf44-b6f1-4720-9ce9-a935d6ea3cbf)

**Comment by xinsuinizhuan** [comment]
> disp->refr_timer = lv_timer_create

it not NULL:
![图片](https://github.com/lvgl/lvgl/assets/40679769/43604c09-3239-4468-80a3-103c7ee1ae92)

**Comment by liamHowatt** [comment]
Strange. I am going to use Windows soon and will look at this. You seem comfortable with debugging. I welcome you to investigate the issue if you want.

**Comment by liamHowatt** [comment]
Yes! I reproduced the problem.

Sysmon expects a display to exist as long as `lv_deinit` hasn't been called, so if all the displays have been deleted then sysmon will encounter the `NULL` access. So your suggested fix is a possible solution. Although, the Windows driver is the only one to not immediately call `lv_deinit()` or `exit(0)` on the last display delete compared to the SDL and X11 drivers, which do. So maybe it would be better to change the Windows driver to do that? It actually does, but in a 200ms timer callback that checks if the display was deleted. Also, the Windows driver calls `lv_display_delete` and `lv_timer_delete` in a separate thread which [should have a mutex](https://docs.lvgl.io/master/porting/os.html#tasks-and-threads), and also add a mutex in the Windows example code. If it can be done without threads and mutexes maybe that'd be even better?

cc @MouriNaruto 

https://github.com/lvgl/lvgl/blob/be4a9d1e735f191151aae5acf4a2018ca2e86f0b/src/drivers/windows/lv_windows_context.c#L626-L644

**Comment by MouriNaruto** [comment]
@liamHowatt By design becuase Windows backend supports multiple LVGL display instances.

We need think more better workaround than other backend does.

Kenji Mouri

**Comment by liamHowatt** [comment]
I appreciate your input. Do you have any thoughts about what kind of workaround would be good?

**Comment by kisvegabor** [comment]
I think it should be fixed by https://github.com/lvgl/lvgl/pull/6073

I'm on Linux, could you try it out on Windows?

**Comment by xinsuinizhuan** [comment]
i try the newest code, still break:
![图片](https://github.com/lvgl/lvgl/assets/40679769/0fe3d12f-4c86-4a77-98e6-330e18a78932)

**Comment by kisvegabor** [comment]
#6073 is not merged yet.

**Comment by liamHowatt** [comment]
Tested just now on Windows. I can confirm the crash does not happen anymore with the sysmon changes for the trivial case.

However, when I create and delete 1M timers in a loop and close the window, the debugger throws a different memory exception each time. It's because LVGL is being reentered by the separate Windows thread when the windows gets closed. For a few different runs, I get a memory access exception [here](https://github.com/lvgl/lvgl/blob/d0a9e8b817132335db504543c16437adf0a244b5/src/misc/lv_ll.c#L233), [here](https://github.com/lvgl/lvgl/blob/d0a9e8b817132335db504543c16437adf0a244b5/src/misc/lv_ll.c#L333), [here](https://github.com/lvgl/lvgl/blob/d0a9e8b817132335db504543c16437adf0a244b5/src/stdlib/builtin/lv_tlsf.c#L591).

I'm using LVGL's allocator with 512 MB space. Here is the test code
```c
    while (1)
    {
        uint32_t time_till_next = lv_timer_handler();
        lv_delay_ms(time_till_next);

        static lv_timer_t * timers[1000000];
        for (int i=0; i<1000000; i++) {
            timers[i] = lv_timer_create(timer_cb, 100, NULL);
        }
        for (int i=0; i<1000000; i++) {
            lv_timer_delete(timers[i]);
        }
    }
```

The main thread is in `lv_timer_create` or `lv_timer_delete` when [this thread](https://github.com/lvgl/lvgl/blob/d0a9e8b817132335db504543c16437adf0a244b5/src/drivers/windows/lv_windows_context.c#L639) calls `lv_display_delete` and `lv_timer_delete`.

**Comment by kisvegabor** [comment]
Great! Thanks for testing it! 

I'm thinking about having `lv_lock()` and `lv_unlock()` functions which are locking/unlocking an `lv_mutex`. These functions could be called in `lv_timer_handler` internally, and the user could use these functions too in the drivers or the application code. 

What do you think?

**Comment by liamHowatt** [comment]
So it's an instance of `lv_mutex_t` that's shared by both the internals and the user? It would be use the mutex implementation from `LV_USE_OS`? It would live in the global, get initialized at init, and be accessed using `lv_(un)lock`. This is a good idea!

For a first PR, are you thinking:

- Add `lv_lock` and `lv_unlock`
- Add init code
- Update thread/mutex docs
- Use the lock in
  - `lv_timer_handler`
  - the Windows driver
- In `lv_windows_context.c` add `#if LV_OS_WINDOWS != 1 #error` because now it depends on the Windows OSAL for the mutex.

One thing though. In my example that causes the memory faults, that would not be fixed by this unless the user adds the `lv_lock` around that code. Is that the expected requirement from the user? Or else some more parts of LVGL would need to acquire the lock. i.e., the allocator, mainly anything in the global singleton.

**Comment by kisvegabor** [comment]
> For a first PR, are you thinking: [...]

Perfect summary! :100: 

> In my example that causes the memory faults, that would not be fixed by this unless the user adds the lv_lock around that code. Is that the expected requirement from the user?

In a general case I assume that
- in the main thread after a quick init the user calls  `lv_timer_handler` (protected internally by `lv_(un)lock`)
- in windows context thread we will add `lv_(un)lock()`

So two weak point remained:
1. any code before `lv_timer_handler` (I think the timer creation/deletion in your code was added there too): If it's a concern the user  can use `lv_(un)lock()` here too.
2. other threads created by the user: we can expect the user to use `lv_(un)lock()`

> Or else some more parts of LVGL would need to acquire the lock. i.e., the allocator, mainly anything in the global singleton.

I would like to avoid that. I think it's a very deep rabbit hole as we need to protect all the widgets too. E.g. what if `lv_label_set_text()` wants to adjust the same label at the same time.

**Comment by liamHowatt** [comment]
All sounds good! I will open a PR after the API retirement.

**Comment by liamHowatt** [comment]
Not stale.
