### ISSUE TITLE
LV Roller text is not centered.

### ISSUE THREAD

**Issue by Kirbyrawr** [kisvegabor/lvgl#6070]
### LVGL version

9.1.0

### What happened?

![image](https://github.com/lvgl/lvgl/assets/3259762/ad4da8e2-8a02-4add-a8fb-68de96f34d2b)

It was fixed here:
https://github.com/lvgl/lvgl/commit/708272c37cacc190e327373f1972dadccbf137e9

However in the LVGL 9.1.0 version it points to LV_PART_MAIN instead of LV_PART_SELECTED as in the issue 3 years ago.
I'm not sure whats the right fix but i leave all the data i can.

With that changed sometimes it looks ok, other times no:
![image](https://github.com/lvgl/lvgl/assets/3259762/874bff63-fc01-40ae-af4b-d74036cee7fe)

### How to reproduce?

https://github.com/lvgl/lvgl/blob/af642572aabbb7a882b7926d78e62c04b967df9c/examples/widgets/roller/lv_example_roller_2.c

Even in the examples is looking wrong.

**Comment by liamHowatt** [comment]
Thanks for linking that v7 fix. That info helped me figure it out. There was a similar issue created this week but for v8.3 #6066. That fix you linked works for the v7 version of lv_roller.c but a fair bit has changed since v7 and there's a better fix for the current v9.1.

Here's a timeline.

v7.0 had the bug
v7 release branch had the fix you linked on May 11, 2021. It works, but I'm not convinced that was the best solution even for that version.
The master branch had 01d1c87 July 5, 2021 which refactored and corrected some of the logic in `draw_main`.
v8.0 release branch had c774c26 July 16, 2021 which was a backport of 01d1c87 for v8.

Now, I believe 01d1c87 / c774c26 almost fixed it but there's a leftover redundancy that forgot to be removed. I'm opening a PR for it now. See the similar issue #6066 for more info. I'm opening an identical PR for v8.4.

**Comment by Kirbyrawr** [comment]
Hi @liamHowatt thank you so much, let me know if i can help or test it.

**Comment by kisvegabor** [comment]
Should be fixed in #https://github.com/lvgl/lvgl/pull/6083 and https://github.com/lvgl/lvgl/pull/6082
