### ISSUE TITLE
LV_COLOR_16_SWAP removal and performance

### ISSUE THREAD

**Issue by codewitch-honey-crisis** [kisvegabor/lvgl#6317]
### Introduce the problem

LV_COLOR_16_SWAP is required on most little endian devices because the pixel format of the display is typically big endian.

And yet it no longer exists in 9+?

This means I cannot use DMA without a performance killing extra scan/modify of the transfer buffer before it is sent.
It's much more efficient - at least generally speaking, not knowing LVGL internals specifically - to do the color byte swap during the draw operations.

Maybe I'm missing something. Maybe there's another way to do this, but it impacts an awful lot of displays if not.

I've given up using 9+ because of it, preferring 8.x or htcw_uix/htcw_gfx instead, and it's primarily because of this issue.

If you removed it, please help me understand the rationale for doing so, if nothing else to make me feel better about it, because it's a real bummer.

### Proposal

Add the color swap feature back?

**Comment by liamHowatt** [comment]
Very recently it was added back in #6225 for this reason.

The function never went away, and now it's back in the refr logic and can be enabled by defining `LV_COLOR_16_SWAP=1` in your build flags. Since it's niche, the setting is not in the configs.

It is a scan/modify as you say, but the function has been implemented in a way that shoud theoretically be very efficient.

**Comment by codewitch-honey-crisis** [comment]
Thank you!
