### ISSUE TITLE
Slider Knob Start Position

### ISSUE THREAD

**Issue by fatiihyildizz** [kisvegabor/lvgl#6847]
### Introduce the problem

Hello,

I want to use the slider's knob object to remain inside the slider. In other words, I don't want the knob image to go outside the slider when I drag the knob to the beginning or the end. How can I do this?

**Comment by kisvegabor** [comment]
Hi,

It's a recurring questions and I think we should really figure it something for it. I have these options in mind:
1. Enable something like `knob_in=true/false` so that LVGL will automatically reduce the movement area of the slider
2. Control it with a padding or margin property of something.

It was asked be SquareLine too, so I cc @leidto

**Comment by kisvegabor** [comment]
We have just discover that it's possible by setting some padding on the slider. 
```c
lv_obj_set_style_pad_hor(slider, 20, 0);
```
